### ISSUE TITLE
How can I get runkratos.exe compiled in Windows (FullDebug)?

### ISSUE THREAD

**Issue by maceligueta** [KratosMultiphysics/Kratos#8909] opened 2021-06-24 20:58 UTC
**Description**
I am getting the error LINK : fatal error LNK1104: cannot open file 'python38_d.lib' when the compilation of runkratos.exe is set to ON.
I made sure that the Python debug libraries are installed (they are in a subfolder called libs in the Python installation folder). However, the linker cannot find that specific file which actually does exist. Do I have to adjust some variable like PYTHON_LIBS or something similar?
Thanks

**Scope**
- Compilation
- KratosCore

**Comment by RiccardoRossi** [comment] 2021-06-24 22:26
uff honestly i don t know.

if you have a more or less working setup we can look into it together

**Comment by roigcarlo** [comment] 2021-06-25 09:16
You need to install python with the debug libraries. It is an option in the advanced section of the python installer, or if you get in through visual studio, a optional install which is listed among the python different components.

If it does not detect the lib, its either because the folder is not in the linking dir of Visual studio, because the lib is incorrect, or because you are linking against a python in another location.

You can force VS to add the directory where you know the lib is by adding it here (photo is not from Kratos, i don't have access to win right now):
![image](https://user-images.githubusercontent.com/1935791/123401032-ac7b9600-d5a6-11eb-82b3-76a85fd470b4.png)

But the problem is likely some of the ones I mentioned above.

**Comment by maceligueta** [comment] 2021-06-28 10:02
Is there a way I can do this if I just use the console for compiling?

**Comment by roigcarlo** [comment] 2021-06-28 10:09
It should be possible with the `/property:xxxxxx=yyyyy` or `/p:XXXX=YY` flagss of msvc, but I ignore how to configure them. Again, it should be automatic if the file exists and the python version that VS is seeing is the correct. 

I would bet that is pointing to another version of python by the look of it....

**Comment by roigcarlo** [comment] 2021-08-24 08:07
@maceligueta chances are that we will drop support for runkratos in the near future in favor of python, python_d, etc...

In this scenario, python_d (which is installed alongside normal python if you select the debug symbols during the installation) should do exactly the same as runkratos compiled in debug mode (even more to be honest)

Closing this. If python_d does not help to solve the problem please reopen

**Closed as completed by roigcarlo** 2021-08-24 08:07 UTC

**Comment by loumalouomega** [comment] 2022-08-03 15:05
Just to say that I am having this problem and this issue is duplicated: https://github.com/KratosMultiphysics/Kratos/issues/7478 and here https://github.com/KratosMultiphysics/Kratos/issues/6400, and the solution of deactivate runkratos worked. Let's kill runkratos!
