### ISSUE TITLE
5.1.1 Release - please take a look

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#695] opened 2017-07-31 10:58 UTC
Dear All, and in particual @KratosMultiphysics/fluid-dynamics , @KratosMultiphysics/structural-mechanics 

we just released the latest Kratos version (5.1.1).

I would like everyone to take a peek at it, and to try to run at least one example. Please tell us if you find problems with the release so that we can release a bugfix.

In order to use it one should install GiD13.1.8 and click on "problemtype->InternetRetrieve->Kratos..." to download and install the latest version.

The MPI version requires one to have the mpi libs and binaries installed from the distro package list. If one chooses mpi as parallelism, the simulation is not launched from within GiD, one should launch from the command line the MPIlauncher.sh which will export the correct paths and submit the mpirun script.
Please note that one can control the use of OMP thread together with the MPI ones by setting 

export OMP_NUM_THREADS=1

cheers
Javi, Pooyan, Carlos & Riccardo

**Comment by philbucher** [comment] 2017-08-01 07:31
Edit 3 I realized I didn't really test the release I think. I will try it as soon as the gid-server is responsive. Nevertheless this might be interesting for the fluid guys, since it is not working on the master branch

Edit I just realized I was on the latest master branch and OMP threads was set to 1
Edit 2 the `MPIlauncher.sh` that Riccardo mentioned was not created

I have tried the release with a small fluid example (non-physical). I tested mpi and non-mpi
Three problems occured:
1. If `OpenMP` is selected in the Parameters but the problem is executed in MPI, I would throw a proper waning (currently it complains that `PARTITION_INDEX`) is not in the variable list.
2. The problem creation worked, but unfortunately I get different results depending on the number of cores I use in MPI @KratosMultiphysics/fluid-dynamics 
3. and sometimes also segfaults (in MPI, happened sometimes when using 8 cores)

I attached the problem case which also contains the gdb output
[test_release.gid.zip](https://github.com/KratosMultiphysics/Kratos/files/1189814/test_release.gid.zip)
To give an impression:
Serial Velocity field in last time step:
![velocity_field_serial](https://user-images.githubusercontent.com/25484702/28813063-f8ed2746-7697-11e7-8a85-fede98da1a09.png)
MPI with 2 processores Velocity field in last time step:
![velocity_field_mpi_2](https://user-images.githubusercontent.com/25484702/28813882-6ecb86bc-769b-11e7-93a5-390417d66429.png)
MPI with 4 processores Velocity field in last time step:
![velocity_field_mpi_4](https://user-images.githubusercontent.com/25484702/28813886-73096762-769b-11e7-9e5e-719b61fdbd21.png)
MPI with 8 processores Velocity field in last time step:
![velocity_field_mpi_8](https://user-images.githubusercontent.com/25484702/28813891-785d09ee-769b-11e7-82f0-2edef1c8e8e1.png)

**Comment by philbucher** [comment] 2017-08-01 08:12
Update:
Since the gid website seems to be down, I downloaded the binaries from the [release page](https://github.com/KratosMultiphysics/Kratos/releases)
The problems of the non-physical solutions remain, works in OpenMP, doesn't work in MPI
At least I didn't get any more segfaults this time

**Comment by jginternational** [comment] 2017-08-01 08:55
@philbucher All the CIMNE servers are down today. 

![image](https://user-images.githubusercontent.com/5918085/28817262-ed1e9b38-76a7-11e7-9393-059d7e486c21.png)

**Comment by RiccardoRossi** [comment] 2017-08-02 07:04
Hi Philip,

can u send me the test example? i tried on my computer a small test with the mpi launcher and it works correctly using 2 to 16 processors. Just wondering if what you experience is a lack of convergence of the linear solver for the specific case you get (it looks like your RE is pretty high, so it might be the case), or something more problematic

**Comment by philbucher** [comment] 2017-08-02 09:04
Hi @RiccardoRossi,
I attached the file in the long post already.
And as I said I didn't put much thought into creating the problem. It worked in serial but not in MPI

**Comment by jcotela** [comment] 2017-08-02 09:46
Hi @philbucher I played a bit with your example. I could not use it as is, because GiD is complaining of some version differences on opening (I'll have to look into it, but it is a separate issue).
I tried to reassing everything (I assumed you used the default 'air' material) and it seems to result in a quite hard linear system, which the default serial default solver (AMGCL) can solve but the default distributed solver (ML) can't. I think this explains the strange behaviours you see in MPI, but I'll try to play a bit with other fluid solvers.

Regarding the segfault, I'll try to reproduce it in master, but I expect it to be related to some of the bugs we fixed for the Release branch and have not yet been ported to master (see #696).

**Comment by philbucher** [comment] 2017-08-02 11:33
@jcotela sorry abt the versioning with gid, I created the example with a one day old version of the problemtype and then transformed it later to the release problemtype, but the behavior was the same. Sorry for this inconvenience.

Regarding the linear solvers settings I think this makes also sense what you say, as I said I didn't put much thought into creating the problem. 

The segfault didn't happen in the release branch, only on the master branch, so I guess that you solved the problem already.

**Comment by RiccardoRossi** [comment] 2017-08-04 06:24
@philbucher then can we close this?

**Comment by philbucher** [comment] 2017-08-04 12:48
@RiccardoRossi since apparently I was the only one having problems I will close it

**Closed as completed by philbucher** 2017-08-04 12:48 UTC
Labels: Release
