### ISSUE TITLE
Discussion about the creation of event macros

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#562] opened 2017-06-28 14:40 UTC
Today I added the error of element inverted to the Structural solids, and I was thinking that maybe there is  a more clever way of solving these issues. Right now with the current `KRATOS_ERROR` or the `KRATOS_THROW_ERROR` we just now that the problem crashed, and if we want to solve the problem we need to start over again the problem and try of figure out where is the origin of the issue.

I was thinking to create a macro or similar called `KRATOS_EVENT` or something similar. We can even create different `KRATOS_EVENT` for each one of the issues that can appear (element inverted, residual not converged, fatal error, etc...). I am taking the idea from the Code_Aster documentation, point 4.3 Event:

http://code-aster.org/doc/default/en/man_d/d9/d9.05.01.pdf

I know that everyone of us is now busy with different projects, I just want to start a discussion of how to effectively tackle these issues.

**Comment by pooyan-dadvand** [comment] 2017-06-29 09:19
Nice idea and conceputally relevant. Nevertheless very complex in practice. I agree that our error handling is primitive and is an ellegant way of exit with more info. A better solution would be to handle the error (by its type) in the main solution and try to roll back the simulation (to previous step) and eliminate the cause of error if is possible (by remeshing, reducing time step, changin contact parameters etc. ) and continue again or simply exit if the error is critical. 

As I said this is very complex in practice due to many many anecdotal details.... but doable for specific solver for a concrete problem.

**Comment by RiccardoRossi** [comment] 2017-11-16 16:00
i would close this since there si no action planned in the short term

**Closed as completed by RiccardoRossi** 2017-11-16 16:00 UTC
Labels: Enhancement, Discussion, Kratos Core
