### ISSUE TITLE
Missing Applications in release

### ISSUE THREAD

**Issue by roigcarlo** [KratosMultiphysics/Kratos#702] opened 2017-08-01 15:44 UTC
ContactMechanicsApplication and PfemSolidMechanicsApplication need to be compiled as well.

**Comment by RiccardoRossi** [comment] 2017-08-01 17:04
this was never in the release plan. Do we really need it? is it called from the interface?

**Comment by roigcarlo** [comment] 2017-08-01 17:06
@josep-m-carbonell told me that is needed by the PfemFluid. As I understand it will not be called from the interface, but used as dependencies

**Comment by RiccardoRossi** [comment] 2017-08-01 20:32
I think that we made an error to include on the last day before the holidays an unscheduled application.
Even if we now include in the binaries the new apps we will have to wait for kike to be back in order to upload them to the gid database. (at least to my understanding)

For now, We can package a new binary and upload it to the grid repository towards the end of August. 

Also since we are in the process of working more on this release, please ensure that the  pfem apps have a readme stating clearly that they can not be used commercially since they link internally to tetgen.

**Comment by jginternational** [comment] 2017-08-02 08:45
@RiccardoRossi This afternoon I can access to the GiD server, so we have access to the publish system

**Comment by pooyan-dadvand** [comment] 2017-08-02 16:04
I agree with @RiccardoRossi that the tetgen license is an issue. Actually I'm not sure is a good idea to have this binary included in this version until we separate the tetgen in a separate one. (with a different release)

**Comment by roigcarlo** [comment] 2017-08-02 16:05
Ok. I will hold this until we agree on something

**Comment by josep-m-carbonell** [comment] 2017-08-02 18:49
The application is not working as it is now. If the correction is not possible it is better to delete it from the release.
@maceligueta @AFranci

**Comment by RiccardoRossi** [comment] 2017-08-04 06:31
so, i am not clear what is the way forward.
I spoke with @jginternational who confirmed that he can push changes to the GiD repo. 

@roigcarlo did u take a look at the gfortrans and other libs errors?

on my side i did detect a minor error in the amgcl_mpi. I have a fix, but i'd like to speak about then with @ddemidov who should be back to work at the beginning of next week.

@josep-m-carbonell @maceligueta @AFranci the last message i am getting is that we should remove the PFEM from the relase. We'll do so unless we get different feedback.

My idea is to package the bugfix release at the beginning of next week (let's say monday afternoon), so that @jginternational can push it to the gid repository (guess that it will happen on wednesday afternoon).

**Comment by AFranci** [comment] 2017-08-04 07:42
go ahead! see you at the next release!

**Comment by jginternational** [comment] 2017-08-07 09:10
Fine @RiccardoRossi , but let me pack the GUI on Wednesday. Minor bugs will be fixed then

**Closed as completed** 2017-09-18 09:54 UTC
Labels: Error, Release
