### ISSUE TITLE
Help needed! FSI Application (GiD v15, Kratos 7.0.2 Mok Example)

### ISSUE THREAD

**Issue by SamiBidier** [KratosMultiphysics/Kratos#7610] opened 2020-10-16 06:57 UTC
Dear Kratos team,
I'm fairly new in the kratos community and am trying to set up a fsi simulation in 3d. I tried basing my application on the mok example, which, however, is not running after meshing (GiD v15, Kratos 7.0.2)

From GiD I get the following warning

![image](https://user-images.githubusercontent.com/72928271/96222579-d21ebd00-0f8c-11eb-9c4c-1d8d37e7862b.png)

resulting in the kratos error

![image](https://user-images.githubusercontent.com/72928271/96222801-30e43680-0f8d-11eb-86fa-1bde871096fb.png)

This is without changing anythin in the example. Could someone verify the behaviour and give me assistance? @rubenzorrilla maybe?

Thanks in advance,
Sami

**Comment by rubenzorrilla** [comment] 2020-10-16 08:30
Dear @SamiBidier ,

It seems that you have not assigned any GiD group in Fluid --> Conditions --> FSI fluid interface. Can you post the generated ProjectParameters.json file here?

**Comment by SamiBidier** [comment] 2020-10-16 08:41
Hi,
thanks for the quick response. here is the json file:

{
    "problem_data"     : {
        "problem_name"  : "test_mik",
        "parallel_type" : "OpenMP",
        "echo_level"    : 0,
        "start_time"    : 0.0,
        "end_time"      : 25.0
    },
    "solver_settings"  : {
        "solver_type"               : "Partitioned",
        "coupling_scheme"           : "DirichletNeumann",
        "echo_level"                : 1,
        "structure_solver_settings" : {
            "solver_type"                        : "Dynamic",
            "model_part_name"                    : "Structure",
            "domain_size"                        : 3,
            "echo_level"                         : 0,
            "analysis_type"                      : "non_linear",
            "time_integration_method"            : "implicit",
            "scheme_type"                        : "bossak",
            "model_import_settings"              : {
                "input_type"     : "mdpa",
                "input_filename" : "test_mik_Structural"
            },
            "material_import_settings"           : {
                "materials_filename" : "StructuralMaterials.json"
            },
            "time_stepping"                      : {
                "time_step" : 0.1
            },
            "line_search"                        : false,
            "convergence_criterion"              : "residual_criterion",
            "displacement_relative_tolerance"    : 0.0001,
            "displacement_absolute_tolerance"    : 1e-9,
            "residual_relative_tolerance"        : 1e-8,
            "residual_absolute_tolerance"        : 1e-10,
            "max_iteration"                      : 20,
            "problem_domain_sub_model_part_list" : ["Parts_Structure"],
            "processes_sub_model_part_list"      : ["DISPLACEMENT_FixedDisplacement","StructureInterface3D_StructureInterface"],
            "rotation_dofs"                      : false
        },
        "fluid_solver_settings"     : {
            "model_part_name"             : "FluidModelPart",
            "domain_size"                 : 3,
            "solver_type"                 : "Monolithic",
            "model_import_settings"       : {
                "input_type"     : "mdpa",
                "input_filename" : "test_mik_Fluid"
            },
            "echo_level"                  : 0,
            "compute_reactions"           : true,
            "maximum_iterations"          : 20,
            "relative_velocity_tolerance" : 1e-8,
            "absolute_velocity_tolerance" : 1e-10,
            "relative_pressure_tolerance" : 1e-8,
            "absolute_pressure_tolerance" : 1e-10,
            "volume_model_part_name"      : 0,
            "skin_parts"                  : [0,"Slip3D"],
            "no_skin_parts"               : [0],
            "time_stepping"               : {
                "automatic_time_step" : false,
                "time_step"           : 0.1
            },
            "formulation"                 : {
                "element_type"             : "vms",
                "use_orthogonal_subscales" : false,
                "dynamic_tau"              : 1.0
            }
        },
        "mesh_solver_settings"      : {
            "echo_level"      : 0,
            "domain_size"     : 3,
            "model_part_name" : "FluidModelPart",
            "solver_type"     : "structural_similarity"
        },
        "coupling_settings"         : {
            "nl_tol"                       : 1e-8,
            "nl_max_it"                    : 25,
            "solve_mesh_at_each_iteration" : true,
            "mapper_settings"              : [{
                "mapper_face"                           : "unique",
                "fluid_interface_submodelpart_name"     : 0,
                "structure_interface_submodelpart_name" : "StructureInterface3D_StructureInterface"
            }],
            "coupling_strategy_settings"   : {
                "solver_type" : "MVQN_recursive",
                "w_0"         : 0.825,
                "buffer_size" : 7
            },
            "structure_interfaces_list"    : ["StructureInterface3D_StructureInterface"],
            "fluid_interfaces_list"        : [0]
        }
    },
    "processes"        : {
        "fluid_initial_conditions_process_list"  : [],
        "fluid_boundary_conditions_process_list" : [{
            "python_module" : "apply_inlet_process",
            "kratos_module" : "KratosMultiphysics.FluidDynamicsApplication",
            "Parameters"    : {
                "model_part_name" : "FluidModelPart.0",
                "variable_name"   : "VELOCITY",
                "modulus"         : "0.1214*(1-cos(0.1*pi*t))*y*(1-y) if t<10 else 0.2428*y*(1-y)",
                "direction"       : "automatic_inwards_normal",
                "interval"        : [0.0,"End"]
            }
        },{
            "python_module" : "apply_outlet_process",
            "kratos_module" : "KratosMultiphysics.FluidDynamicsApplication",
            "Parameters"    : {
                "model_part_name"    : "FluidModelPart.0",
                "variable_name"      : "PRESSURE",
                "constrained"        : true,
                "value"              : 0.0,
                "hydrostatic_outlet" : false,
                "h_top"              : 0.0
            }
        },{
            "python_module" : "apply_noslip_process",
            "kratos_module" : "KratosMultiphysics.FluidDynamicsApplication",
            "Parameters"    : {
                "model_part_name" : "FluidModelPart.0"
            }
        },{
            "python_module" : "assign_vector_variable_process",
            "kratos_module" : "KratosMultiphysics",
            "Parameters"    : {
                "model_part_name" : "FluidModelPart.0",
                "variable_name"   : "MESH_DISPLACEMENT",
                "constrained"     : [true,true,true],
                "value"           : [0.0,0.0,0.0],
                "interval"        : [0.0,"End"]
            }
        },{
            "python_module" : "assign_vector_variable_process",
            "kratos_module" : "KratosMultiphysics",
            "Parameters"    : {
                "model_part_name" : "FluidModelPart.0",
                "variable_name"   : "MESH_DISPLACEMENT",
                "constrained"     : [false,false,true],
                "value"           : [0.0,0.0,0.0],
                "interval"        : [0.0,"End"]
            }
        },{
            "python_module" : "python_process",
            "kratos_module" : "KratosMultiphysics",
            "Parameters"    : {
                "model_part_name" : "FluidModelPart.0"
            }
        },{
            "python_module" : "apply_slip_process",
            "kratos_module" : "KratosMultiphysics.FluidDynamicsApplication",
            "process_name"  : "ApplySlipProcess",
            "Parameters"    : {
                "model_part_name" : "FluidModelPart.Slip3D"
            }
        }],
        "fluid_gravity"                          : [{
            "python_module" : "assign_vector_by_direction_process",
            "kratos_module" : "KratosMultiphysics",
            "process_name"  : "AssignVectorByDirectionProcess",
            "Parameters"    : {
                "model_part_name" : "FluidModelPart.0",
                "variable_name"   : "BODY_FORCE",
                "modulus"         : 0.0,
                "constrained"     : false,
                "direction"       : [0.0,-1.0,0.0]
            }
        }],
        "fluid_auxiliar_process_list"            : [],
        "structure_constraints_process_list"     : [{
            "python_module" : "assign_vector_variable_process",
            "kratos_module" : "KratosMultiphysics",
            "Parameters"    : {
                "model_part_name" : "Structure.DISPLACEMENT_FixedDisplacement",
                "variable_name"   : "DISPLACEMENT",
                "constrained"     : [true,true,true],
                "value"           : [0.0,0.0,0.0],
                "interval"        : [0.0,"End"]
            }
        }],
        "structure_loads_process_list"           : [{
            "python_module" : "python_process",
            "kratos_module" : "KratosMultiphysics",
            "Parameters"    : {
                "model_part_name" : "Structure.StructureInterface3D_StructureInterface"
            }
        }]
    },
    "output_processes" : {
        "gid_output" : [{
            "python_module" : "gid_output_process",
            "kratos_module" : "KratosMultiphysics",
            "process_name"  : "GiDOutputProcess",
            "help"          : "This process writes postprocessing files for GiD",
            "Parameters"    : {
                "model_part_name"        : "Structure.computing_domain",
                "output_name"            : "test_mik_structure",
                "postprocess_parameters" : {
                    "result_file_configuration" : {
                        "gidpost_flags"       : {
                            "GiDPostMode"           : "GiD_PostBinary",
                            "WriteDeformedMeshFlag" : "WriteDeformed",
                            "WriteConditionsFlag"   : "WriteConditions",
                            "MultiFileFlag"         : "SingleFile"
                        },
                        "file_label"          : "step",
                        "output_control_type" : "step",
                        "output_frequency"    : 1,
                        "body_output"         : true,
                        "node_output"         : false,
                        "skin_output"         : false,
                        "plane_output"        : [],
                        "nodal_results"       : ["DISPLACEMENT","REACTION","VELOCITY","ACCELERATION"],
                        "gauss_point_results" : ["VON_MISES_STRESS"]
                    },
                    "point_data_configuration"  : []
                }
            }
        },{
            "python_module" : "gid_output_process",
            "kratos_module" : "KratosMultiphysics",
            "process_name"  : "GiDOutputProcess",
            "help"          : "This process writes postprocessing files for GiD",
            "Parameters"    : {
                "model_part_name"        : "FluidModelPart.fluid_computational_model_part",
                "output_name"            : "test_mik_fluid",
                "postprocess_parameters" : {
                    "result_file_configuration" : {
                        "gidpost_flags"       : {
                            "GiDPostMode"           : "GiD_PostBinary",
                            "WriteDeformedMeshFlag" : "WriteDeformed",
                            "WriteConditionsFlag"   : "WriteConditions",
                            "MultiFileFlag"         : "SingleFile"
                        },
                        "file_label"          : "time",
                        "output_control_type" : "step",
                        "output_frequency"    : 1,
                        "body_output"         : true,
                        "node_output"         : false,
                        "skin_output"         : false,
                        "plane_output"        : [],
                        "nodal_results"       : ["VELOCITY","PRESSURE","MESH_DISPLACEMENT"],
                        "gauss_point_results" : []
                    },
                    "point_data_configuration"  : []
                }
            }
        }]
    }
}

I see the problem "[0]" where the fluid interface should be ...

But GiD should write it there according to the input of the mok example, right?
![image](https://user-images.githubusercontent.com/72928271/96236255-16658980-0f9c-11eb-977a-e30ca1fcef85.png)

**Comment by rubenzorrilla** [comment] 2020-10-16 08:50
From the image I guess that you used the predefined 3D example in the GiD GUI. Can you confirm this? (I think there's a problem with the model part naming in the tcl script that generates the case).

**Comment by SamiBidier** [comment] 2020-10-16 08:52
yes i can confirm that I onlz opened the example, meshed it and tried to calculate it. I  simply wanted to re-start from that example, as I ran into the problem with my fluid/solid interface

**Comment by rubenzorrilla** [comment] 2020-10-18 13:30
> yes i can confirm that I onlz opened the example, meshed it and tried to calculate it. I simply wanted to re-start from that example, as I ran into the problem with my fluid/solid interface

OK. I'll try to reproduce the error. I'll let you know as soon as I have more information. Thanks for reporting @SamiBidier !

**Comment by rubenzorrilla** [comment] 2020-10-19 07:30
I tried the predefined example in the GUI and there is no error in my case. Are you using the current master version of the GUI?

**Comment by SamiBidier** [comment] 2020-10-19 07:47
Hi, I'm using the official GiD release version: GiD internal version: 15.0 ( 64 bits) with Kratos 7.0.2
Would you suggest using the developer version? Maybe I'll try a re-installation.

**Comment by rubenzorrilla** [comment] 2020-10-19 17:45
That Kratos release is way old... @jginternational is it possible to update the internet retrieve Kratos version for the GiD 15.0? @jginternational

**Comment by jginternational** [comment] 2020-10-19 19:56
Sure @rubenzorrilla There a newer release 7.1.5 https://github.com/KratosMultiphysics/GiDInterface/releases/tag/release-7.1.5

Also we can talk with @roigcarlo about a future release

**Comment by rubenzorrilla** [comment] 2020-10-20 07:47
@SamiBidier would you mind trying the latest release @jginternational is pointing to? (should be as easy as changing the current `kratos.gid` folder by this one inside the `problemtypes` folder of your GiD installation directory.

**Comment by SamiBidier** [comment] 2020-10-20 08:11
@rubenzorrilla Already done. Everything seems to work now. Thanks a lot for the quick support!

**Comment by rubenzorrilla** [comment] 2020-10-20 08:13
Cool! Then, I'm closing the issue. Feel free to reopen it if necessary. Thanks!

**Closed as completed by rubenzorrilla** 2020-10-20 08:13 UTC
Labels: Help Wanted

**Comment by roigcarlo** [comment] 2020-10-20 08:28
@jginternational  Just jumping in to say that we released 8.0 on may. you can fetch it from here https://github.com/KratosMultiphysics/Kratos/tree/v8.0.1

Next release should fall during nov/dec, but everything seems to be a little delayed because covid, so I cannot guarantee a date until we speak about it.
