### ISSUE TITLE
Error while loading VTK results in Paraview

### ISSUE THREAD

**Issue by ggiraldo** [KratosMultiphysics/Kratos#9983] opened 2022-06-23 16:55 UTC
**Description**
Field results from structural application are not loaded in Paraview.

This is the error message:

```
Generic Warning: In C:\glr\builds\paraview\paraview-ci\build\superbuild\paraview\src\VTK\IO\Legacy\vtkDataReader.cxx, line 1534
Error reading ascii data. Possible mismatch of datasize with declaration.

ERROR: In C:\glr\builds\paraview\paraview-ci\build\superbuild\paraview\src\VTK\IO\Legacy\vtkDataReader.cxx, line 2054
vtkUnstructuredGridReader (00000203A65EA080): Unsupported data type: 
```

**Scope**
Postprocessing of VTK results in Paraview.

**To Reproduce**
Run the 'Vertical Movement' example from Contacts Mechanics Application.

**Expected behavior**
The results in VTK format are loaded in Paraview for postprocessing.

**Environment**
- OS: Windows 11
- Branch: latest version from pip
- Python 3.9
- Paraview 5.10.1

**Comment by UmarSaeedMalik** [comment] 2022-07-28 13:24
Hello,

I don't know if this error has multiple causes, but i had the same and i was able to identify the cause (for my case) and solve it. Here it is:

After some examination I found out that this problem was coming because in some output variables in my .vtk files, I had big numbers such as 1e-36 (that are out of scope of the float data type in paraview).

 To correct this, you can edit the file "vtk_output.cpp" and in the desired functions (for my variables it was the function : VtkOutput::WriteVectorContainerVariable), change the string ""  float\n"" to ""  double\n"", so that now the paraview .vtk reader will read the variable as double instead of float and would have more precision and thus the problem would most probably be solved. Here is a SC of my changed function:
![Capture](https://user-images.githubusercontent.com/103575989/181515857-1c0bb260-6455-4619-be48-16d652f9f587.PNG)


I hope this helps.

Best wishes.

**Comment by loumalouomega** [comment] 2022-07-28 13:26
@pablobecker had this very same problem. i think the issue is duplicated

**Comment by pablobecker** [comment] 2022-07-28 13:40
how old is the pip version?
@loumalouomega fixed this a month ago 
See https://github.com/KratosMultiphysics/Kratos/issues/9969

**Comment by loumalouomega** [comment] 2022-07-28 13:43
> how old is the pip version? @loumalouomega fixed this a month ago See #9969

So it was me who fix it?, nice

**Comment by pablobecker** [comment] 2022-07-28 13:43
haha, you even forget your PRs

**Comment by loumalouomega** [comment] 2022-07-28 13:47
> #9976

It was a month ago. I was in rush mode in my last days in my previous work. I don't have a lot of memories of those days :P

**Comment by UmarSaeedMalik** [comment] 2022-07-28 14:28
> @pablobecker had this very same problem. i think the issue is duplicated

@loumalouomega Thank you. I didn't see that thread before. Its solved.

**Comment by UmarSaeedMalik** [comment] 2022-07-28 14:29
> Hi everyone,
> 
> In my case the issue was caused by the writing of the normals in the VTK file. Apparently the normal was not defined at some nodes and the placeholder NaN causes the error in Paraview.
> 
> I was able to circumvent the issue by disabling the writing of the normals, but I guess that the issue is not solved.

@ggiraldo  Oh okay, yes i remember, i also took them out and it works :D

**Comment by pablobecker** [comment] 2022-07-28 14:59
in the meantime, switching to binary format could work

**Comment by loumalouomega** [comment] 2022-07-28 15:00
> in the meantime, switching to binary format could work

@roigcarlo  did a release 16 minutes ago https://github.com/KratosMultiphysics/Kratos/releases

**Comment by rubenzorrilla** [comment] 2022-07-28 15:01
Closing the issue as this should be solved in the fresh release.

**Closed as completed by rubenzorrilla** 2022-07-28 15:01 UTC

**Comment by roigcarlo** [comment] 2022-07-28 16:01
Just to comment, binaries are still being upload, it may take until tomorrow morning to be available worldwide
