### ISSUE TITLE
[Discussion] Ensuring Committee Reviews

### ISSUE THREAD

**Issue by matekelemen** [KratosMultiphysics/Kratos#11529] opened 2023-08-30 17:42 UTC
*Continuing the discussion from #11528.*

## Repo State

Thankfully, the Kratos project is quite lively and there are lots of people contributing to it by opening plenty of PRs. This is nice, but it also creates some issues that must be solved to keep these people working on this repository instead of just forking it at working on their own.

The problem is that any PR touching `Core` is subject to unclear review requirements that possibly involve the `Technical Committee`, which consists of only a handful of people who are already extremely busy and have to divide their attention between Kratos and numerous other duties.

## Problem

`Core` is used by all applications and as such, is extremely important to be clear, correct, concise and efficient. Keeping it that way requires PRs touching `Core` to be vetted by people who are not only well-versed in every aspect of software development, but also know what's currently in the project and what will be changed/added in the future.

**The topic of this issue is finding a good solution to making sure these extra rigorous reviews get carried out for PRs that need it.**

## Current Solution

I've seen a couple of cases where people not in the `Technical Committee` block a PR on accounts of "preventing accidental merge"s, often without proper review, in order to ensure that a committee member sees the PR. This is wrong for many reasons:
- the only option of the blocker to remove their block is by approving the PR.
- the blocker now has to keep track of the PR and review it properly every time the PR's author comes up with a new version.
- people depending on the PR will now have to wait until not only for a committee member's review, but also for the blocker's approval (subject to holidays, lack of time, forgetfullness, etc.).
- last but not least: blocking a PR is serious. It means that there's a grave problem with the changes that *must not* make it into `master` without correction. Therefore, blocking without a proper reason can be both depressing and infuriating to the author.

## Suggestions

We're not the first project with such problems: requiring reviews from a specific group of people is what [code owners](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) are for. @ddiezrod 's argument against it is that the `Technical Committee` is already busy and shouldn't be notified about **every** PR that targets `Core`. However, we can't have it both ways: we can't require a committee review **and** save them from performing said review. Here are the things that pop into my mind that could help:
- reduce the committees responsibilities
   - further partition `Core` into packages. Some could require a committee review, while others could require a review from another group.
   - have committee members delegate their review to another group that has the sufficient skills in the PR's topic.
   - have a little trust in Kratos developers, and extend the committee.
- restructure the `Core` / `Applications` hierarchy into something more granular. There's plenty of stuff in `Core` that is required by 2-3 apps while completely irrelevant to the rest. These could be grouped into intermediate `Extension`s that live between `Core` and `Application`s.

Finally, I think that we should have a little more faith in people developing Kratos. I have a hard time believing that people here will deliberately go against the community to speed-merge their stuff.

##

Let me know what you think.

**Comment by matekelemen** [comment] 2023-08-30 22:25
> > people depending on the PR will now have to wait until not only for a committee member's review, but also for the blocker's approval (subject to holidays, lack of time, forgetfullness, etc.).
>
> During this summer I have replied everytime I have been mentioned, I have done some reviews and removed my block from several PRs.

I didn't mean to single you out. The problem is with the practice of blocking as a means of ensuring a review, and the extra work and possible delays they entail, no matter who issues the block.

Of course there are examples when the blocker can respond to changes in the PR in time, but why impose this extra responsibility when it doesn't solve the problem but possibly adds latency to PR approvals?

**Comment by AlejandroCornejo** [comment] 2023-08-31 05:21
I'll try to give my opinion about this issue:

**On the one hand**, as @matekelemen mentions, Kratos has been growing a lot in the last years, and not only in lines of code, but also is efficient ways of ensuring that the added code is clean, correct and compatible (CI, tests, etc). In this regard, the involvement of the @KratosMultiphysics/technical-committee is crucial and, even though their revisions in the core PRs are intense, I understand that it is the way to go to avoid future "pain".

**However**, sometimes it is inevitable to feel that the progress of an implementation slows down a lot (with 1 or 2 year old PRs) with this process. This can make it tempting as a developer to implement code at the application level because I will be able to make use of it much more easily and **know how much time I will invest in its development (if you able to merge)**. I say this because sometimes you can get blocked because the proposed solution is not optimal but no alternative is proposed (due to a lack of time mainly) and the PR becomes stale (https://github.com/KratosMultiphysics/Kratos/pull/11071).
Obviously, the whole Kratos community loses out as the same code can be in several Apps or even the code never reaches the master branch.

**Regarding the Subcommittees**, some of us are already included in those sub committees but we have not been as productive as I thought we would be. 
Mainly I think that the subcommittees, instead of going "looking for work" on the PR list as it is done so far, should receive PRs directly from the technical and provide empowerment on them. This way we have a meaningful binding relationship between the committees.

Finally, about the _blocking just in case_ thing :') : I think that it does not make much sense to do it anymore in Kratos. Now that we have the code owners (CORE, StructuralMechanics, FluidDynamics, etc) we are enforcing that the most approppriate team will review the code. 
I would only **block_just_in_case** if I know that I am using a certain part of the core or app that it is going to be modified and I would like to check its compatibility (maybe my app is not included in the CI testing environment)

**Comment by loumalouomega** [comment] 2023-08-31 08:12
> **Regarding the Subcommittees**, some of us are already included in those sub committees but we have not been as productive as I thought we would be. Mainly I think that the subcommittees, instead of going "looking for work" on the PR list as it is done so far, should receive PRs directly from the technical and provide empowerment on them. This way we have a meaningful binding relationship between the committees.

I agree with you, maybe we wil be more motivated if we have some actual decision power, not just an intermediate review process-

**Comment by roigcarlo** [comment] 2023-08-31 08:29
First let me say that currently the code-owner restriction to approve or merge a PR **is not currently enforced** and is used only to automatically assign the PR to the proper developers and teams. What the code-owners from the TC have right now is a special permission to dismiss blocks from people outside the TC. 

The problem is that we often not have time to see if the block is a real block or a just in case block so unless is very clear do no not dismiss those reviews anyway....

We took that decision specifically because we didn't want to make a PR that touched files from several applications from different maintainers to last forever or require 14+ approvals before merge (as some of them are already slow enough to review). For example, see the list of approvals I would need for #11526.

This always have been under the assumption that people would review the code in good faith and wait until everyone that was implicated in the PR had the opportunity to have their saying. The reality (and I am including myself), is that is very tempting to message some to tell him: "Hey, take a quick look to my PR" or directly "Hey approve that is very minor". As we have had bad experiences with this before, is very easy for us to pre-block something even if we are not going to review it only to stop it from being merged because we suspect it could break. And as  @matekelemen says this is wrong.

As for the suggestions:

> further partition Core into packages. Some could require a committee review, while others could require a review from another group.

Agree with @loumalouomega, in most of the cases it does not make sense that a Pr is blocked if someone touched only processes and utilities. I even would extend that to search structures, part of the I/O, mappers, modelers etc (not saying no-one should review but its not critical) 

> have committee members delegate their review to another group that has the sufficient skills in the PR's topic.
> have a little trust in Kratos developers, and extend the committee.

Also agree that's the implementation committee, but I would also extend non critical matters (changes that do not break the api, or are restricted to a limited context even if in the core) to basically anyone that has been contributing to Kratos for more than a couple of years and is familiar with the code.

> restructure the Core / Applications

While not what you propose, for some time now we have wanted to trim the list of official applications and leave the rest as research ones. This would allow us to reduce the amount of code. That would considerably reduce the amount of PR that the TC has to take into account when making big changes to the core or considering PR. (Either by moving research applications to another repo, leaving them outside the code owner mechanism or simply having them properly identified)

In regards of trimming the core, I agree, but for that we have to identify exactly what parts are not being used. It would be easy if we can guarantee that all apps have proper tests that extensively covers all the functionality they use and trace the usages in the core, but I am afraid is not the case. We can extract that info we the current coverage and make a map, but it will be incomplete or at least not the full picture. Anyway we can make the effort nevertheless.

**Comment by ddiezrod** [comment] 2023-09-01 10:02
I think one of the ways to speed up the reviewing process and give back some meaning to the @KratosMultiphysics/implementation-committee would be to let this sub-committee decide which changes should be discussed inside @KratosMultiphysics/technical-committee and which ones are less important, so they can be approved by the sub-committee. We tried to do it the other way around, but it did not really work and actually, the @KratosMultiphysics/implementation-committee has not held any meeting in months...

**Comment by matekelemen** [comment] 2023-09-04 11:11
> Mainly I think that the subcommittees, instead of going "looking for work" on the PR list as it is done so far, should receive PRs directly from the technical and provide empowerment on them. This way we have a meaningful binding relationship between the committees.

> I think one of the ways to speed up the reviewing process and give back some meaning to the https://github.com/orgs/KratosMultiphysics/teams/implementation-committee would be to let this sub-committee decide which changes should be discussed inside https://github.com/orgs/KratosMultiphysics/teams/technical-committee and which ones are less important, so they can be approved by the sub-committee.

I agree with both; I think pushing (*a reasonable amount of*) obligations on committees is something we should try out. I have no particular preference between the top-down or bottom-up approaches, but relying on people to look for work themselves doesn't work.

**Comment by matekelemen** [comment] 2023-09-04 11:33
> > further partition Core into packages. Some could require a committee review, while others could require a review from another group.
>
> Agree with @loumalouomega, in most of the cases it does not make sense that a Pr is blocked if someone touched only processes and utilities. I even would extend that to search structures, part of the I/O, mappers, modelers etc (not saying no-one should review but its not critical)

So these could be grouped into subpackages of `Core` that have more relaxed review requirements.

**Comment by RiccardoRossi** [comment] 2023-09-04 12:29
To give my 2 cents, and pending a discussion about this in the  @KratosMultiphysics/technical-committee (with the inevitable delay), we could introduce some "triage" mechanism to see what is not conflictive and does not require a committee decision.

**Comment by pooyan-dadvand** [comment] 2024-11-18 10:41
As we discussed in the Kratos workshop 2024, we just started to check with the mechanism of assigning champions to improve the review situation. 

@matekelemen, let's close this and see how the new process goes. We can reopen it again if the champion approach is not sufficient.

**Closed as completed** 2024-11-18 10:53 UTC
Labels: Discussion, Proposal
