### ISSUE TITLE
test_patch_test_shells_orthotropic.py failing in full debug

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#1234] opened 2017-12-22 20:25 UTC
Hi @philbucher i am assigning it to you, only so that you reassign to the person that did the ortothropic shell. (sorry i don't know if it is Klaus, Andreas...)

 python3 test_patch_test_shells_orthotropic.py 
 |  /           |             
 ' /   __| _` | __|  _ \   __|
 . \  |   (   | |   (   |\__ \ 
_|\_\_|  \__,_|\__|\___/ ____/
           Multi-Physics 5.3.0-7713b69-FullDebug
Importing    KratosStructuralMechanicsApplication
     KRATOS   ___|  |                   |                   |                     
            \___ \  __|  __| |   |  __| __| |   |  __| _` | |                   
                  | |   |    |   | (    |   |   | |   (   | |                     
            _____/ \__|_|   \__,_|\___|\__|\__,_|_|  \__,_|_| MECHANICS     
terminate called after throwing an instance of 'Kratos::Exception'
  what():  Error: attempting to do a GetValue for: YOUNG_MODULUS_X variable #1139 unfortunately the variable is not in the database and the operations is not threadsafe (this function is being called from within a parallel region)

in kratos/containers/data_value_container.h:199:TDataType& DataValueContainer::GetValue(const Variable<TDataType>&) [with TDataType = double]
   kratos/solving_strategies/schemes/residualbased_incrementalupdate_static_scheme.h:291:void ResidualBasedIncrementalUpdateStaticScheme<TSparseSpace, TDenseSpace>::CalculateSystemContributions(Element::Pointer, ResidualBasedIncrementalUpdateStaticScheme<TSparseSpace, TDenseSpace>::LocalSystemMatrixType&, ResidualBasedIncrementalUpdateStaticScheme<TSparseSpace, TDenseSpace>::LocalSystemVectorType&, Element::EquationIdVectorType&, ProcessInfo&) [with TSparseSpace = UblasSpace<double, boost::numeric::ublas::compressed_matrix<...>, boost::numeric::ublas::vector<double> >; TDenseSpace = UblasSpace<double, boost::numeric::ublas::matrix<double>, boost::numeric::ublas::vector<double> >; Element::Pointer = boost::shared_ptr<Element>; ResidualBasedIncrementalUpdateStaticScheme<TSparseSpace, TDenseSpace>::LocalSystemMatrixType = boost::numeric::ublas::matrix<double>; ResidualBasedIncrementalUpdateStaticScheme<TSparseSpace, TDenseSpace>::LocalSystemVectorType = boost::numeric::ublas::vector<double>; Element::EquationIdVectorType = __debug::vector<long unsigned int>]

**Comment by philbucher** [comment] 2017-12-25 13:53
currently fixing it in [my branch](https://github.com/KratosMultiphysics/Kratos/tree/StructMech/shells-new-testing-and-cleanup)

**Comment by philbucher** [comment] 2018-01-11 15:45
Hi @RiccardoRossi 
I checked the code and I need your help on this one.
The problem is that we create a Property object that is later being passed to the constLaw ([see here](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/StructuralMechanicsApplication/custom_utilities/shell_cross_section.cpp#L446)). This is thread safe in my opinion, but the unfortunately the data_container always checks if it is executed in parallel.

The problem now is to make it work. Ofc I could also pass the original properties (with variable `SHELL_ORTHOTROPIC_LAYERS`) but then I don't know from which row (i.e. which ply) to extract the data from in the constitutive law ([here](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/StructuralMechanicsApplication/custom_constitutive/linear_elastic_orthotropic_2D_law.cpp#L164))

I hope you understand what I mean

**Comment by philbucher** [comment] 2018-01-30 08:41
Ping @RiccardoRossi

**Comment by philbucher** [comment] 2018-02-02 18:39
ping @RiccardoRossi

**Comment by RiccardoRossi** [comment] 2018-02-05 11:28
Hi Philip,

i am not sure if i understand your problem.
Access to Properties is threadsafe IF THE VARIABLE IS ALREADY THERE. It is not otherwise... and  i guess this is the error you are getting.

In order to make it threadsafe you should first ensure that the variable is actually set before accessing to it

**Comment by philbucher** [comment] 2018-02-05 16:58
fixed in #1444

**Closed as completed by philbucher** 2018-02-05 16:58 UTC
Labels: Bug, Help Wanted
