### ISSUE TITLE
Behr tests failing in debug mode

### ISSUE THREAD

**Issue by jcotela** [KratosMultiphysics/Kratos#3595] opened 2018-12-06 16:11 UTC
Looks like the Behr tests are failing when compiling kratos in `FullDebug` mode. This type of error is normally caused by assigning or reading from invalid positions in a dense matrix/vector (say position 3,1 in a 2x3 matrix) and corresponds to an undetected memory leak in release mode. I could not look into it in detail right now but the errors ultimately arise from `ComputeGaussPointBehrSlipRHSContribution` in  `Kratos/applications/FluidDynamicsApplication/custom_conditions/navier_stokes_wall_condition.cpp`. Preliminary debugging suggests that the problems are related to this section at the end of the function:
https://github.com/KratosMultiphysics/Kratos/blob/71447da75ac1be64d6fb55679151ff82a82d395a/applications/FluidDynamicsApplication/custom_conditions/navier_stokes_wall_condition.cpp#L612-L633

I would have guessed that `CompleteSigmaInterpolated` should be of size `TNumNodes` and `NodalEntriesRHS[nnode]` of size `TDim+1`, but changing those was not enough to fix the issue (so don't take my word for it).

The specific error messages follow:
```
Ran 517 of 518 test cases in 2.02772s. 3 failed:
    TestElementTwoFluidNavierStokes2D3NHydrostaticBehr Failed with message: 
        Error: bad argument

in /home/jcotela/Kratos/applications/FluidDynamicsApplication/custom_conditions/navier_stokes_wall_condition.cpp:634:void NavierStokesWallCondition<2, 2>::ComputeGaussPointBehrSlipRHSContribution(NavierStokesWallCondition::VectorType &, const NavierStokesWallCondition::ConditionDataStruct &) [TDim = 2, TNumNodes = 2]
   /home/jcotela/Kratos/applications/FluidDynamicsApplication/custom_conditions/navier_stokes_wall_condition.cpp:137:virtual void NavierStokesWallCondition<2, 2>::CalculateLocalSystem(NavierStokesWallCondition::MatrixType &, NavierStokesWallCondition::VectorType &, ProcessInfo &) [TDim = 2, TNumNodes = 2]

    TestElementTwoFluidNavierStokes2D3NStressBehr Failed with message: 
        Error: bad argument

in /home/jcotela/Kratos/applications/FluidDynamicsApplication/custom_conditions/navier_stokes_wall_condition.cpp:634:void NavierStokesWallCondition<2, 2>::ComputeGaussPointBehrSlipRHSContribution(NavierStokesWallCondition::VectorType &, const NavierStokesWallCondition::ConditionDataStruct &) [TDim = 2, TNumNodes = 2]
   /home/jcotela/Kratos/applications/FluidDynamicsApplication/custom_conditions/navier_stokes_wall_condition.cpp:137:virtual void NavierStokesWallCondition<2, 2>::CalculateLocalSystem(NavierStokesWallCondition::MatrixType &, NavierStokesWallCondition::VectorType &, ProcessInfo &) [TDim = 2, TNumNodes = 2]

    TestElementTwoFluidNavierStokes3D4NHydrostaticBehr Failed with message: 
        Error: bad argument

in /home/jcotela/Kratos/applications/FluidDynamicsApplication/custom_conditions/navier_stokes_wall_condition.cpp:634:void NavierStokesWallCondition<3, 3>::ComputeGaussPointBehrSlipRHSContribution(NavierStokesWallCondition::VectorType &, const NavierStokesWallCondition::ConditionDataStruct &) [TDim = 3, TNumNodes = 3]
   /home/jcotela/Kratos/applications/FluidDynamicsApplication/custom_conditions/navier_stokes_wall_condition.cpp:137:virtual void NavierStokesWallCondition<3, 3>::CalculateLocalSystem(NavierStokesWallCondition::MatrixType &, NavierStokesWallCondition::VectorType &, ProcessInfo &) [TDim = 3, TNumNodes = 3]

```

**Comment by swenczowski** [comment] 2018-12-06 20:10
I apologize for the faulty implementation. The problem seemed to be caused by the size of the projection matrix. This and following up issues are addressed in #3601.

Thank you very much for the hint - I switch from Debug to FulllDebug for the further development.

**Closed as completed** 2018-12-07 19:32 UTC
Labels: Applications, Testing
