### ISSUE TITLE
Issue with Co-Simulation

### ISSUE THREAD

**Issue by juanjuradov** [KratosMultiphysics/Kratos#9961] opened 2022-06-15 16:57 UTC
**Description**
I'm trying to do Turek's problem with Co-Simulation, however, it doesn't work. In addition, I've tried with the same settings FSI solvers from Turek's problem and it works. 

**Scope**
- CoSimulationAppliction
- MappingApplication
- StructuralMechanicsApplication
- FluidDynamicsApplication
- MeshMovingApplication
- ConstitutiveLawsApplication
- LinearSolversApplication
- ConvectionDiffusionApplication

**Turek's Co-Simulation problem**
I've uploaded a file with the Co-Simulation codes if someone could help me.
[TurekCoSim.zip](https://github.com/KratosMultiphysics/Kratos/files/8911373/TurekCoSim.zip)

Many thanks,

Juan

**Comment by rubenzorrilla** [comment] 2022-06-16 05:46
Any hint @KratosMultiphysics/cosimulation ?

**Comment by philbucher** [comment] 2022-06-19 10:32
Hey,
What is the problem?
Can you please provide some more info as to what is failing?

**Comment by juanjuradov** [comment] 2022-06-28 18:54
Hi all,
I tried out to make some changes such as a different solving order (structure first and then fluid) and convergence accelerator (aitken). However, the results in Y-MESH DISPLACEMENT are still too small values (10^-6) but in pressure I got similar values compared to the Turek’s FSI exercise.
I would like to remark that the parameters of material and settings are identical from FSI solver.
I attach a figure of Y-MESH DISPLACEMENT in time step 10.1.
![TurekCoSim-timestep-10 1](https://user-images.githubusercontent.com/107507656/176258451-1c191dc5-8f77-4e69-bdeb-96df2db3a30c.jpeg)

**Comment by mpentek** [comment] 2022-06-29 11:46
Could you post a download link with the full setup? If not possible here publicly, send me a private message if you are ok with that. I would go through your setup.

**Comment by juanjuradov** [comment] 2022-06-29 13:50
Yes sure! I've uploaded a download link with the latest changes in this post called ''TurekCoSim.zip''. 
[TurekCoSim.zip](https://github.com/KratosMultiphysics/Kratos/files/9011000/TurekCoSim.zip)
Let me know if you have any issue to download it, please!

Thanks,

Juan

**Comment by rubenzorrilla** [comment] 2022-07-04 07:12
@mpentek @philbucher Any hint about this? We thoroughtly checked the co-simulation settings taking the Mok test as reference and everything seems to be OK. The test settings are algo correct.

**Comment by philbucher** [comment] 2022-07-04 11:05
I will have a detailed look asap, unfortunately super busy these days
Will try my best to donut this week

**Comment by mpentek** [comment] 2022-07-05 08:53
Short on time :-)

Anyway, the other suggestion would be to try the FractionalStep solver instead of the Monolithic. Also, as you say fluid loads (pressures) seem to be correct, is that you verify the quantities which are mapped (sum of Reaction on the fluid side) and received (sum of Point Loads on the structure side). Alternatively, you could even apply some forces of similar magnitude simply on a structural model, to try to rule out sources of errors in mapping and fluid. Those are also the steps I typically take in these situations.

**Comment by philbucher** [comment] 2022-07-09 19:39
I briefly checked your input and noticed that you are not using the `use_transpose` flag when mapping the loads. This will lead to losses of loads if the number of nodes on the fluid side is smaller than on the structure
Can you try this before we look into it in more detail?

**Comment by philbucher** [comment] 2022-07-09 19:58
Check the[readme](https://github.com/KratosMultiphysics/Kratos/tree/master/applications/MappingApplication#advanced-usage) (end of this section) for info on `use_transpose` aka conservative mapping

**Comment by mpentek** [comment] 2022-07-19 07:49
> I will have a detailed look asap, unfortunately super busy these days Will try my best to do it this week

Good catch @philbucher

**Comment by mpentek** [comment] 2022-07-19 07:49
> I briefly checked your input and noticed that you are not using the `use_transpose` flag when mapping the loads. This will lead to losses of loads if the number of nodes on the fluid side is smaller than on the structure Can you try this before we look into it in more detail?

Good catch @philbucher

**Comment by rubenzorrilla** [comment] 2022-07-19 08:03
Hey! I didn't have the time to go deeper in this but just mentioning that we tried with both  `use_transpose` and without and didn't work.

**Comment by mpentek** [comment] 2022-08-05 11:41
The ALE boundary conditions are wrong.

Now I changed it, please see the difference in:

Assigning 0.0 to the cylinder:
```
{
                    "python_module": "assign_vector_variable_process",
                    "kratos_module": "KratosMultiphysics",
                    "process_name": "AssignVectorVariableProcess",
                    "Parameters": {
                        "model_part_name": "FluidModelPart.NoSlip2D_Cylinder",
                        "variable_name": "MESH_DISPLACEMENT",
                        "interval"        : [0.0,"End"],
                        "constrained"     : [true,true,true],
                        "value"           : [0.0,0.0,0.0]
                    }
                }
```
Fixing the tail of the cylinder, where the motion from the structure is prescribed:
```
{
                    "python_module": "fix_vector_variable_proces
[TurekCoSimDEBUG.zip](https://github.com/KratosMultiphysics/Kratos/files/9268224/TurekCoSimDEBUG.zip)
s",
                    "kratos_module": "KratosMultiphysics",
                    "process_name": "FixVectorVariableProcess",
                    "Parameters": {
                        "model_part_name": "FluidModelPart.FluidNoSlipInterface2D_FluidInterface",
                        "variable_name": "MESH_DISPLACEMENT",
                        "interval"        : [0.0,"End"],
                        "constrained"     : [true,true,true]
                    }
                }
```

Once this started moving on the fluid side, the previous settings did not converge for me. I switched it to Fractional Step from Monolithic to test. You should figure out your specific settings for fomulations and solvers to achieve physically meaningful results.

You should close this thread once you check out the changes.

**Closed as completed** 2022-08-08 07:50 UTC
Labels: Help Wanted

**Comment by rubenzorrilla** [comment] 2022-08-09 09:42
@mpentek many thanks for the effort. Yes, the issue is clear.

What I do in the `FSIApplication` is to automatically do the fixity of all the FSI interfaces, which are listed in the `solver_settings` inside the solver. Long story short, the user is only asked for the `MESH_DISPLACEMENT` BCs.

I understand that this cannot be as easily achieved in the `CoSimulationApplication`. Maybe we can think on automatically do this with the prescribed variables in all the Dirichlet-type coupling interfaces. The point on doing this is that we need to distinguish which are Dirichlet...
