### ISSUE TITLE
Acceptance of alternative tokens in C++

### ISSUE THREAD

**Issue by maceligueta** [KratosMultiphysics/Kratos#708] opened 2017-08-03 14:34 UTC
According to this website: http://cpprocks.com/if-arr-not_eq-0-and-not-false-alternative-tokens-in-c/ and others: https://stackoverflow.com/questions/1703979/which-c-logical-operators-do-you-use-and-or-not-and-the-ilk-or-c-style-oper (sorry if I am not checking the actual official source) the alternative tokens are accepted officially in c++.
Apparently, Visual Studio does not accept them unless you activate the option /Za.
I think it would be worth adding it, better than reminding everyone constantly that they do not have to use them in linux. 
@roigcarlo told me that it's possible to disable these alternative tokens in gcc by means of a flag, but still I think this would be going against the main stream. 
What do you think? Can we try to add '/Za' to the windows compilation?
@KratosMultiphysics/technical-committee @jcotela

**Comment by RiccardoRossi** [comment] 2017-08-03 14:52
just to be sure i understand your proposal:

you are suggesting to allow writing

if(a and b)

as a synonim of 

if(a && b)

and telling that it is standard compliant and that a macro in win would allow that. 
is my resume correct? If it is so, i would not be against...

**Comment by maceligueta** [comment] 2017-08-03 14:54
It is correct. It would allow 'not', 'and' and 'or'.
A compiler flag allows it in Windows. I am not sure if it uses macros, though.

**Comment by roigcarlo** [comment] 2017-08-03 15:25
Thx @maceligueta , I was not aware of this, I thought this was only a gcc compatiblity issue with C having this operators but it appears that they are completely valid

Technically /Za  works to some extend. I have just try it and MSVC gives problems while combining some of the alternate tokens (<%%> <::> and others...) , but we could add it for the binary ones.

Aside from this I still thing that we should stick to use the main form and not the alternate one. But if everyone wants I will add the flag...

**Comment by jcotela** [comment] 2017-08-03 15:45
Personally, I prefer the the "mainstream" keywords (`&&`, `||`, etc.), but I don't have a strong opinion on this. Reading the stackoverflow thread in @maceligueta's post, I'm not clear if in MSVC one should include the [iso646](http://www.cplusplus.com/reference/ciso646/) header or not to use the new keywords in C++. Can those of you that have tried it confirm? I don't have a windows computer at hand to test it.

**Comment by roigcarlo** [comment] 2017-08-03 15:48
No no, it's enough setting the /Za, no includes needed ( probably the flag
includes the iso646 automatically )

**Comment by roigcarlo** [comment] 2017-08-04 15:33
After trying to do a release with the flag it seems that it introduces erros in boost and python. Not sure why, but let me try next week in more depth.

**Edit**

It seems that Za conflicts with C++11 according to MS:

> Other compiler options used with /Za can affect how the compiler ensures standards conformance. For example, /Za and /fp (Specify Floating-Point Behavior) may result in floating-point type promotion behavior that does not conform to the ISO C99 or C++11 standards.

**Comment by pooyan-dadvand** [comment] 2017-08-04 18:38
I understand that adding this flag won't harm anyone but for me the main stream is without alternative support and I don't see it more readable considering that it also changes the `#` and `{}` for keyboards that does not have them. 

Saying all this I'm not against adding this flag.

**Comment by roigcarlo** [comment] 2017-08-04 18:41
@pooyan-dadvand No, it does not work, we just tested it with @pablobecker this afternoon. I cannot tell you exactly what's happening but it makes some parts of the code (quaternion.h and pytime.h ) stop compiling.

Let me figure out why this happens before adding it.

**Comment by roigcarlo** [comment] 2017-12-13 11:19
Took some time to look into this today. Now I can confirm wee cannot use neither the `/Za` option nor use the `<ciso646>` header. The reason for the flag was stated before. The problem with the header is, as I susspected, that it conflicts with boost. Among several other places, onc that is very important to us, the python interface. Precisely here:

```C++
#if PY_VERSION_HEX >= 0x03000000
    BOOST_PYTHON_BINARY_OPERATOR(truediv, rtruediv, /)
#else
    BOOST_PYTHON_BINARY_OPERATOR(div, rdiv, /)
#endif
BOOST_PYTHON_BINARY_OPERATOR(mod, rmod, %)
BOOST_PYTHON_BINARY_OPERATOR(lshift, rlshift, <<)
BOOST_PYTHON_BINARY_OPERATOR(rshift, rrshift, >>)
BOOST_PYTHON_BINARY_OPERATOR(and, rand, &)
BOOST_PYTHON_BINARY_OPERATOR(xor, rxor, ^)
BOOST_PYTHON_BINARY_OPERATOR(or, ror, |)
BOOST_PYTHON_BINARY_OPERATOR(gt, lt, >)
BOOST_PYTHON_BINARY_OPERATOR(ge, le, >=)
BOOST_PYTHON_BINARY_OPERATOR(lt, gt, <)
BOOST_PYTHON_BINARY_OPERATOR(le, ge, <=)
BOOST_PYTHON_BINARY_OPERATOR(eq, eq, ==)
BOOST_PYTHON_BINARY_OPERATOR(ne, ne, !=)
# undef BOOST_PYTHON_BINARY_OPERATOR
```

By adding the `<ciso646>` header depending on the order of the includes we may end having a situation where most of the macros in boost/python/operators.hpp will be expanded incorrectly, as for example "and" will be expanded as ||, which is used as a ##variable, long story short, it tries to compile the variable `op_||`.

Just to mention a example. Maybe if we remove boost we can reopen this again, but for now I'll close it.

**Closed as completed by roigcarlo** 2017-12-13 11:19 UTC
