### ISSUE TITLE
can't open file 'MainKratos.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by Jiguojijing** [KratosMultiphysics/Kratos#777] opened 2017-09-17 05:18 UTC
Dear all,
I am a beginner and I followed the steps in this tutorial：https://github.com/KratosMultiphysics/Kratos/wiki/Getting-Kratos-binaries-(via-GiD).
But when I try to  compute a simple case, an error occurs as: "can't open file 'MainKratos.py': [Errno 2] No such file or directory". NEED your help, thanks!

**Comment by loumalouomega** [comment] 2017-09-17 08:19
Questions:

* Linux or Windows?
* Can you screen-shoot the problem?
* Can you run the problem directly ? (going to the folder and running the script there)

**Comment by Jiguojijing** [comment] 2017-09-17 15:53
Thanks! @loumalouomega 
I installed GiD in windows 10 and the error is shown in the following pictures.I have checked the directer:D:\Program Files\GiD\GiD 13.1.8d, but can not find such a file named “MainKratos.py”.
![image](https://user-images.githubusercontent.com/31837833/30522473-251869a8-9c03-11e7-9c3d-55ce8c840f89.png)
![image](https://user-images.githubusercontent.com/31837833/30522477-29273eb6-9c03-11e7-8650-04689f144309.png)

PS: I also followed the steps in https://github.com/KratosMultiphysics/Kratos/wiki/Windows-Install , and Successfully generated the file “KratosMultiphysics.sln” in D:\Kratos\cmake_build. But when I try to Compiling Kratos in visual studio 2015 community update2， lots of error (error LNK2019;error LNK2001;error LNK1120;error MSB3073...)occurs, as shown in “Compiling error.txt”. The last step “Test and Usage” was failed.This two pictures shows what’s in D:\Kratos & D:\Kratos\cmake_build after Compiling.Do I need to compile it if I want to use Kratos in GiD?
[Compiling error.txt](https://github.com/KratosMultiphysics/Kratos/files/1309188/Compiling.error.txt)
![image](https://user-images.githubusercontent.com/31837833/30522466-03293fc0-9c03-11e7-94bd-3d1116e5be0f.png)
![image](https://user-images.githubusercontent.com/31837833/30522469-0b49ea4c-9c03-11e7-9041-d54d3c2ab5f6.png)

**Comment by Jiguojijing** [comment] 2017-09-17 16:02
![image](https://user-images.githubusercontent.com/31837833/30522552-8371e28a-9c04-11e7-8ab0-1c0162b677a1.png)
![image](https://user-images.githubusercontent.com/31837833/30522557-9f501e36-9c04-11e7-90a1-6936449b94fc.png)

**Comment by loumalouomega** [comment] 2017-09-17 16:29
MainKratos.py does not exist in origin, it is copied from other python script in the problem type folder. Maybe it is a problem of permissions. In any case this looks more like a problem of the interface. I opened an issue in the respective place. Respect the compilation I am not an expert in Windows compilation

**Comment by loumalouomega** [comment] 2017-09-17 16:31
Can you screenshoot the folder where the problem is created?

**Comment by Jiguojijing** [comment] 2017-09-17 17:09
Yeah, maybe it's just a problem of registration, but how could get an password for this problem type?
![image](https://user-images.githubusercontent.com/31837833/30523059-f4275cbe-9c0c-11e7-9651-061a0f593d37.png)
![image](https://user-images.githubusercontent.com/31837833/30523081-5d449054-9c0d-11e7-991d-8241c0cd32ed.png)

**Comment by Jiguojijing** [comment] 2017-09-17 17:47
@roigcarlo   Sir, please have a look at my problem of Compiling Kratos in Windows 10.

**Comment by loumalouomega** [comment] 2017-09-17 18:02
For the screenshoot of the folder I meant to the problem you created, something like test.gid

**Comment by roigcarlo** [comment] 2017-09-17 18:05
Dear @Jiguojijing, I will try to help.
Let's stick with the Kratos from this tutorial: https://github.com/KratosMultiphysics/Kratos/wiki/Getting-Kratos-binaries-(via-GiD).

The problem here seems to be a missing file, MainKratos.py.  Resgistration is not a problem at this stage, Trial version only limits the size of the simulations.

This problematic file is generated by GiD when you first run the simulation, and it is stored in the folder you saved your simulation.
I see that you created a cube in GiD. We would need to see the contents of the folder where the simulation was saved. 

Could you show us the content of that folder?

**Comment by Jiguojijing** [comment] 2017-09-18 00:09
This is the floder of the case I created.
![image](https://user-images.githubusercontent.com/31837833/30526139-6ad8a968-9c48-11e7-915e-153dc0d7e4ee.png)

**Comment by roigcarlo** [comment] 2017-09-18 00:23
That seems to be the problem, the file is missing and it should have been
copied there. Let me speak with GiD team in the morning ( 2AM here sorry ).
Probably there is something wrong with the problemtype.

**Comment by Jiguojijing** [comment] 2017-09-18 01:13
Thank you very much!

**Comment by roigcarlo** [comment] 2017-09-18 07:46
I have spoken with GiD team and we suspect that is a TCL error, that means than, in the process of generating the files it has encounter a problem and it has stoped. This is most likely caused by some condition being missing or some value causing an exception.

In order to check that, please could you send us either:
- This image with higher resolution (left box is the one that shows the main error)
![image](https://user-images.githubusercontent.com/1935791/30532761-47d6054c-9c56-11e7-9af2-a6144c6d5307.png)

- Send us a zip with the case you generated

In the meantime you can also check that everything runs normally to discard any other issue by running one of the automatically generated examples Problems that support that like Fluid 2d, etc.. have a book icon ( below the X ) that generate automatically the example to run.

P.s. @loumalouomega do not send messages with my account!

**Comment by jginternational** [comment] 2017-09-18 09:31
Hi @Jiguojijing ,
As @roigcarlo said, the important text in the screenshot is  the one of the left box, but I can't read it in the picture.

It would be nice to have that zip with the case, in order to detect the problem.

**Comment by Jiguojijing** [comment] 2017-09-18 11:02
This is the box on on th left.
 ![image](https://user-images.githubusercontent.com/31837833/30538995-01744986-9ca3-11e7-8ae0-74ff5b7ec5cc.png)
a screenshoot can not show it all, and the full text is here:

Error (l685): You have not assigned a proper entity to group Parts Auto1
STACK:
You have not assigned a proper entity to group Parts Auto1
    while executing
"error [= "You have not assigned a proper entity to group $group"]"
    (procedure "write::writeGroupElementConnectivities" line 32)
    invoked from within
"write::writeGroupElementConnectivities $gNode $elem"
    (procedure "write::writeElementConnectivities" line 8)
    invoked from within
"write::writeElementConnectivities"
    (procedure "Structural::write::writeModelPartEvent" line 17)
    invoked from within
"Structural::write::writeModelPartEvent"
    ("eval" body line 1)
    invoked from within
"eval $wevent"
    (procedure "writeAppMDPA" line 17)
    invoked from within
"writeAppMDPA $appid"
    (procedure "::write::writeEvent" line 19)
    invoked from within
"::write::writeEvent $filename"
    (procedure "::AfterWriteCalcFileGIDProject" line 4)
    invoked from within
"::AfterWriteCalcFileGIDProject D:/Users/qijie/Desktop/gidtry/gidtry1.gid/gidtry1.dat 0"

Here is the zip file of this case:
[gidtry1.gid.zip](https://github.com/KratosMultiphysics/Kratos/files/1310438/gidtry1.gid.zip)

**Comment by jginternational** [comment] 2017-09-18 13:37
Hi @Jiguojijing 

The only thing you are missing is to mesh.

As I can see from your zip, there is no mesh assigned to any group (geometry is properly assigned).
This happends when your mesh is generated before assign the tree conditions.
Just mesh again and run.

Extra:
You can see the Layers and Groups window in GiD, and list the entities assigned to the groups.

https://www.gidhome.com/documents/referencemanual/GENERAL%20ASPECTS/Utilities%20Menu/Layers%20and%20groups%20(only%20Preprocessing)

- Click on Utilities - Layers and Groups
- The new window appears in the right
- Click on the Groups tab
- Select a group and right button to see the options
- List the assigned entities

**Comment by Jiguojijing** [comment] 2017-09-19 00:58
I have remeshed it, it's OK now. Thank you all!

**Comment by loumalouomega** [comment] 2017-09-19 08:43
Can we close this?

**Comment by roigcarlo** [comment] 2017-09-19 08:46
I understand its ok nw, please @Jiguojijing if there is any other problem open a new issue.

**Closed as completed by roigcarlo** 2017-09-19 08:46 UTC
