### ISSUE TITLE
Adding external forces on DEM-FEM boundaries in Kratos DEM 

### ISSUE THREAD

**Issue by giacomoperino** [KratosMultiphysics/Kratos#7993] opened 2020-12-16 21:04 UTC
Hi to everyone, I am new to GitHub and I am very pleased to join. 

I am using Kratos 7.1.5 in particular the DEM pack, doing the pre and post processing on Gid 15.0.1.

I am working on a model to analyse the railway ballast behavoir. So I have created the ballast as DEM material and the concrete sleepers. The concrete sleepers are DEM-FEM boundaries, with free body motion, so I have applied forces and mass to each of them. 

The problem is that Gid does not introduce the forces on the DEM-FEMboundary.mdpa file so the solver does not recognize. 

Is it possible to add the forces directly from the DEM-FEMboundary-mdpa file? I post an example of my file .mdpa, for a DEM-FEM group I have in the model:

****Begin SubModelPart 4 // DEM-FEM-Wall - group identifier: 1
  Begin SubModelPartData // DEM-FEM-Wall. Group name: 1
    RIGID_BODY_MASS 215
    RIGID_BODY_CENTER_OF_MASS [3] (0.68,2.54,0.0)
    RIGID_BODY_INERTIAS [3] (94.3,1.75,95.3)
    VELOCITY_START_TIME 0.0
    VELOCITY_STOP_TIME 100.0
    FIXED_MESH_OPTION 0
    RIGID_BODY_MOTION 0
    FREE_BODY_MOTION 1
    IS_GHOST 0
    IDENTIFIER 1
  End SubModelPartData
  Begin SubModelPartNodes**
     77909
     77918
     80610
     80622
     83903
     83915
     86154
     86162
  End SubModelPartNodes
Begin SubModelPartConditions
    107955
    107956
    107957
    107958
    107959
    107960
    107961
    107962
    107963
    107964
    107965
    107966
End SubModelPartConditions**

From what I have understood, there is a way to add the forces directly in this file, bypassing the Gid interface but I have no idea of what commands I need to write 

Could anyone help me on it? 

Thank you very much in advance :)

**Comment by joaquinirazabal** [comment] 2020-12-17 11:18
@KratosMultiphysics/dem

Hi @giacomoperino, thank you for your comment, I checked and you are right, the External Forces are not being written correctly, not in Kratos Kratos 7.1.5 nor in Kratos 8.1.0. For the moment, you can add the appropriate line in the DEM-FEMboundary-mdpa file:

Begin SubModelPart 4 // DEM-FEM-Wall - group identifier: 1
Begin SubModelPartData // DEM-FEM-Wall. Group name: 1
RIGID_BODY_MASS 215
RIGID_BODY_CENTER_OF_MASS [3] (0.68,2.54,0.0)
RIGID_BODY_INERTIAS [3] (94.3,1.75,95.3)
**EXTERNAL_APPLIED_FORCE [3] (100, 100, 100)**
VELOCITY_START_TIME 0.0
VELOCITY_STOP_TIME 100.0
FIXED_MESH_OPTION 0
RIGID_BODY_MOTION 0
FREE_BODY_MOTION 1
IS_GHOST 0
IDENTIFIER 1
End SubModelPartData
Begin SubModelPartNodes
77909
77918
80610
80622
83903
83915
86154
86162
End SubModelPartNodes
Begin SubModelPartConditions
107955
107956
107957
107958
107959
107960
107961
107962
107963
107964
107965
107966
End SubModelPartConditions

Then you can run the problem from terminal.

**Comment by giacomoperino** [comment] 2020-12-17 16:20
Thank you very much @joaquinirazabal !

**Comment by maceligueta** [comment] 2020-12-18 11:47
Hi @giacomoperino ,  thanks for reporting the bug. For faster response from the DEM team, make sure you tag us in the text (adding @KratosMultiphysics/dem in any spot in the text we get a notification in our email inbox).

**Comment by giacomoperino** [comment] 2020-12-18 15:42
@KratosMultiphysics/dem thank you very much. I solved the previous problem with the help of @joaquinirazabal 

I am running a simulation by command prompt on windows and I have this message error:

ModelPartIO:   [Reading Nodes    : 102028 nodes read]
ModelPartIO:   [Reading Elements : Traceback (most recent call last):
  File "MainKratos.py", line 33, in <module>
    DEMAnalysisStageWithFlush(model, project_parameters).Run()
  File "C:\Users\giaco\Downloads\kratos-7.0-win-64\kratos-7.0-win-64\KratosRelease\kratos\python_scripts\analysis_stage.py", line 47, in Run
    self.Initialize()
  File "C:\Users\giaco\Downloads\kratos-7.0-win-64\kratos-7.0-win-64\KratosRelease\applications\DEMApplication\python_scripts\DEM_analysis_stage.py", line 285, in Initialize
    self.ReadModelParts()
  File "C:\Users\giaco\Downloads\kratos-7.0-win-64\kratos-7.0-win-64\KratosRelease\applications\DEMApplication\python_scripts\DEM_analysis_stage.py", line 387, in ReadModelParts
    model_part_io_spheres.ReadModelPart(self.spheres_model_part)
RuntimeError: Error: Element ContactInfoSphericParticle3D is not registered in Kratos. Please check the spelling of the element name and see if the application which containing it, is registered correctly. [Line 102050 ]

in kratos/sources/model_part_io.cpp:1422:ModelPartIO::ReadElementsBlock
   kratos/sources/model_part_io.cpp:1458:ModelPartIO::ReadElementsBlock
   kratos/sources/model_part_io.cpp:526:ModelPartIO::ReadModelPart

KRATOS TERMINATED WITH ERRORS

I am using a kratos 7.0 by command prompt but if I use Gid with the version 7.1 it works properly. What could it be? 

@maceligueta 

Thank you very much in advance!!

**Comment by joaquinirazabal** [comment] 2020-12-18 15:52
Hi @giacomoperino the problem is this line in the DEM.mdpa

Begin Elements ContactInfoSphericParticle3D

You are trying to use an element that it was not registered in Kratos in previous versions. It was my fault, the files in the files I sent you I made that mistake.

Change that line to:

**Begin Elements SphericParticle3D**

It should work.

**Comment by maceligueta** [comment] 2020-12-18 15:53
Hi, it could be that this element (ContactInfoSphericParticle3D) was added to Kratos between version 7.0 and 7.1. It is not one of the oldest elements, so maybe it was not being registered by the time we released Kratos 7.0.
I can't think of any other possible cause, as the registration of an element is pretty simple and should work fine when reading an mdpa file.

**Comment by maceligueta** [comment] 2020-12-18 15:54
I see that you said the same thing, @joaquinirazabal

**Comment by giacomoperino** [comment] 2020-12-18 16:10
Ok, I thought it was something like this
Now it works
Thank you very much @maceligueta @joaquinirazabal wish you a nice week-end :) 💯

**Comment by maceligueta** [comment] 2020-12-19 10:01
Hey @joaquinirazabal, I am trying to fix the bug reported by @giacomoperino initally in the GiD GUI.
I just double checked that it is possible to write (in the `mdpa `file) something like:
```
EXTERNAL_APPLIED_FORCE_X 100
EXTERNAL_APPLIED_FORCE_Y 100
EXTERNAL_APPLIED_FORCE_Z 100
```
Apart from the classic version:
`EXTERNAL_APPLIED_FORCE [3] (100, 100, 100)`

This means that we can write the force component by component, as it is presented in the GUI.

However, I don't think we should go this way, because this format would not be valid with tables. Is there a plan on how to write this properly in the `mdpa `file?

**Comment by joaquinirazabal** [comment] 2020-12-21 07:42
Hi @maceligueta, in this moment you can impose the forces in Kratos by value:
EXTERNAL_APPLIED_FORCE [3] (100, 100, 100)
or by table:
TABLE_NUMBER_FORCE [3] (1,2,3)

I am not sure which is the best way to write this in the .mdpa from the GUI, but now is working if you write it manually.

**Comment by maceligueta** [comment] 2020-12-21 16:50
I think this is a good opportunity to write it as a `Process`, just like the rest of Kratos do. We should allow a constant value, a table or an analytical function for each component independently. 
Let's leave this issue open as a reminder that a process must be implemented and the GUI must write this process [pending task].

**Comment by philbucher** [comment] 2020-12-21 18:47
I think those processes already exist in the core

**Comment by mczaplinski89** [comment] 2021-01-27 10:27
Dear All,
I would like to apply a loading-unloading sequence to a DEM-FEM boundary. It should look something like this:
time force
0    0
1    100
2    0

Please help me to apply a loading table directly to .mdpa file
Best regards

**Comment by maceligueta** [comment] 2021-01-27 20:09
@joaquinirazabal is the expert, but he is off these days, I'll answer as soon as I have run a test.

**Comment by joaquinirazabal** [comment] 2021-01-28 08:06
Hi, sorry for the late response.

If you want to apply the loading-unloading sequence with a table, the DEMFEM_boundary.mdpa file should read like (example for applying the load in the Z direction):

Begin ModelPartData
//  VARIABLE_NAME value
End ModelPartData

Begin Properties 1
   ...
End Properties

**Begin Table 1 TIME EXTERNAL_APPLIED_FORCE_Z
0.0 0.0
1.0 100.0
2.0 0.0
End Table**

Begin Nodes
   ...
End Nodes

Begin Conditions RigidFace3D3N
   ...
End Conditions

Begin SubModelPart 1
  Begin SubModelPartData 
    ...
    **TABLE_NUMBER_FORCE [3] (0,0,1)**
    **FREE_BODY_MOTION 1**
    ...
  End SubModelPartData
  Begin SubModelPartNodes
    ...
  End SubModelPartNodes
Begin SubModelPartConditions
    ...
End SubModelPartConditions
**Begin SubModelPartTables
     1
End SubModelPartTables**
End SubModelPart

In this example you can see that the table is defined, then in the SubModelPartData chunk the TABLE_NUMBER_FORCE is set to (0,0,1) as the Table number 1 is applied to the Z coordinate (if, in additon, Table number 2 is applied to the X direction that line should read TABLE_NUMBER_FORCE [3] (2,0,1)). Finally, note that you should specify the Tables that apply to that Submodelpart in the SubModelPartTables chunk.

Hope I have explained it clearly, any doubt you have, tell me.

**Comment by rubenzorrilla** [comment] 2023-06-23 08:13
Closing as it seems to be solved. @giacomoperino feel free to reopen if needed.

**Closed as completed by rubenzorrilla** 2023-06-23 08:13 UTC
