### ISSUE TITLE
[FluidDynamicsApplication]  CFD --> REACTION

### ISSUE THREAD

**Issue by soudah** [KratosMultiphysics/Kratos#6009] opened 2019-11-28 23:57 UTC
Dear All, 

In collaboration with @rubenzorrilla, we are using the REACTION forces to compute the Wall Shear Stress(WSS) over a cilindrical tube, mainly thinking on Biomedical problems. Next image shows the     | REACTION |. 

![REACTION](https://user-images.githubusercontent.com/9455032/69835222-34b97e00-1240-11ea-96f9-c9033d0b53fa.PNG)

Next image shows the NORMAL

![imagen](https://user-images.githubusercontent.com/9455032/69835267-86620880-1240-11ea-8bf4-bef130c8a416.png)

Then, we use " VariableRedistributionUtility::DistributePointValues(rModelPart, REACTION, FACE_LOAD, tolerance, max_it)"  to project the reactions over the nodes of the mesh, getting:

![imagen](https://user-images.githubusercontent.com/9455032/69835314-d9d45680-1240-11ea-96b1-89ea5189ef58.png)

Based on that projection (FACE LOAD), the Wall Shear Stress is computed. 

![imagen](https://user-images.githubusercontent.com/9455032/69835445-076dcf80-1242-11ea-9d49-12e58c9c4907.png)

In order to try to improve the results, @rubenzorrilla told me that I had to decrease the tolerance of the solver.  Right now, the parameters of the solver are:

        "relative_velocity_tolerance" : 0.000000001,
        "absolute_velocity_tolerance" : 1e-9,
        "relative_pressure_tolerance" : 0.000000001,
        "absolute_pressure_tolerance" : 1e-9,

The results showed are using these parameters, so my question is: 

How we can improve the results? How we can avoid this marbled effect? Any ideas?

Thank you very much,

p.D: The implementation is done in: FluidDynamicalBiomedicalApplication. This application derives from FluidDynamicsApplication.

@rubenzorrilla @RiccardoRossi @jcotela @philbucher @KratosMultiphysics/fluid-dynamics @KratosMultiphysics/fluid-maintainers

**Comment by RiccardoRossi** [comment] 2019-11-29 07:54
do you have any sort of regularity in the thickness of the first element layer in the vicinity of the boundary?

**Comment by soudah** [comment] 2019-11-29 09:57
Thanks Riccardo.

These are the results using a "strutured and center-strutured mesh". 

![imagen](https://user-images.githubusercontent.com/9455032/69860518-bf2ccc80-1296-11ea-83b1-41f58b73cbd7.png)

Right now I will try with the same mesh + Boundary layer.

**Comment by soudah** [comment] 2019-11-29 10:39
These are the results with Boundary Layer. The results improve a lot, but there are some peak values on the WSS. I am reviwing how the WSS is computed. But WSS is just only the norm of projection of the face_Load over the elements. 

![imagen](https://user-images.githubusercontent.com/9455032/69863173-7415b800-129c-11ea-828f-392fdd990950.png)

**Comment by rubenzorrilla** [comment] 2019-11-29 10:49
Considering that the `REACTION`, which is converted to `FACE_LOAD`, and the `NORMAL` are smooth, I dare say that the problem is in the `WSS` calculation.

**Comment by philbucher** [comment] 2020-04-21 14:11
can this be closed?

**Comment by Virginiasam** [comment] 2020-09-05 00:36
Hi All, 
I am also interested in computing WSS. Do you have this i1mplemented to share? 
I am currently testing Kratos for microfluidics applications.
Thks!

**Comment by rubenzorrilla** [comment] 2020-09-05 12:33
We plan to retake this during the upcoming weeks. @Virginiasam we will let you know as soon as we merge the changes. 😉

**Comment by Virginiasam** [comment] 2020-09-09 16:24
Thank you @rubenzorrilla ! Looking forward

**Comment by rubenzorrilla** [comment] 2022-09-23 08:38
Closing as it seems to not be an issue anymore.

As a note for the record, I'd like to add that all the WSS-like capabilities are now collected in the `FluidDynamicsBiomedicalApplication`.

**Closed as completed by rubenzorrilla** 2022-09-23 08:38 UTC
Labels: Help Wanted, Question
