### ISSUE TITLE
FluidDynamic Example

### ISSUE THREAD

**Issue by fdifrison** [KratosMultiphysics/Kratos#1578] opened 2018-02-27 20:15 UTC
Hi KratosTeam,
@rubenzorrilla 

I have just pulled and recompiled Kratos, downladed the problemtype for Gid, and tried to lunch one of the preloaded example (cylinder in airflow).
Both in 2d and in 3d , with fractional and monolithic, i got the same error.
I didn't touch anything, just opened and meshed.
In both Gid interface and .json the density is set to 1.0
Any clues?

Thanks for your help 

Traceback (most recent call last):
  File "MainKratos.py", line 36, in <module>
    solver.ImportModelPart()
  File "/home/bestofdicea/Kratos/applications/FluidDynamicsApplication/python_scripts/navier_stokes_solver_vmsmonolithic.py", line 110, in ImportModelPart
    self._set_physical_properties()
  File "/home/bestofdicea/Kratos/applications/FluidDynamicsApplication/python_scripts/navier_stokes_solver_vmsmonolithic.py", line 177, in _set_physical_properties
    raise Exception("DENSITY set to {0} in Properties {1}, positive number expected.".format(rho,el.Properties.Id))
Exception: DENSITY set to 0.0 in Properties 1, positive number expected.

**Comment by rubenzorrilla** [comment] 2018-02-28 11:51
Hi @fdifrison,

The problem is that neither the DENSITY nor the DYNAMIC_VISCOSITY are being written in the *.mdpa properties section.

@jginternational just told me that he did some changes in the properties writting and this is probably related to that. 

Thanks for reporting the error.

**Comment by philbucher** [comment] 2018-02-28 12:38
Maybe it would be a good idea to add proper error messages for such cases?

**Comment by sarti-luca** [comment] 2018-03-01 15:10
Hi @rubenzorrilla 

I'm testing this new version, I got another error using the fractional step scheme when I compute the drag file.
The error is:

STEP =  1
TIME =  0.1
terminate called after throwing an instance of 'Kratos::Exception'
  what():  Error: Unexpected value for FRACTIONAL_STEP index: 0


in /home/bestofdicea/Kratos/applications/FluidDynamicsApplication/custom_elements/fractional_step.cpp:53:void FractionalStep<TDim>::CalculateLocalSystem(FractionalStep<TDim>::MatrixType&, FractionalStep<TDim>::VectorType&, ProcessInfo&) [with unsigned int TDim = 2u; FractionalStep<TDim>::MatrixType = boost::numeric::ublas::matrix<double>; FractionalStep<TDim>::VectorType = boost::numeric::ublas::vector<double>]
   /home/bestofdicea/Kratos/applications/FluidDynamicsApplication/custom_elements/fractional_step.cpp:57:void FractionalStep<TDim>::CalculateLocalSystem(FractionalStep<TDim>::MatrixType&, FractionalStep<TDim>::VectorType&, ProcessInfo&) [with unsigned int TDim = 2u; FractionalStep<TDim>::MatrixType = boost::numeric::ublas::matrix<double>; FractionalStep<TDim>::VectorType = boost::numeric::ublas::vector<double>]

terminate called recursively
terminate called recursively
Aborted (core dumped)

-----
The error doesn't appear:
- with the same project but without computing the drag file;
- with the same project using the monolithic scheme instead the fractional.

This is the project
[drag.gid.tar.gz](https://github.com/KratosMultiphysics/Kratos/files/1771567/drag.gid.tar.gz)

Thanks,
Luca

**Comment by rubenzorrilla** [comment] 2018-03-02 12:55
Hi @sarti-luca ,

As you can see in PR #1595 it was a particularity of the FS scheme (which I did not take into account when coding the drag utils). Thanks for reporting.

**Comment by jginternational** [comment] 2018-03-05 09:20
The last [pull request merged ](https://github.com/KratosMultiphysics/GiDInterface/commit/3e9b86c5e6b5c858ec51564eb2feb301c51c3cac) should fix this issue.

**Closed as completed by jginternational** 2018-03-05 09:20 UTC
Labels: Applications
