### ISSUE TITLE
ModelPart - name

### ISSUE THREAD

**Issue by PhilippeBussetta** [KratosMultiphysics/Kratos#1789] opened 2018-04-02 16:44 UTC
I have a problem with Windows in debug on the initialisation of `ModelPart`
It is not possible to read the `NewName` initialised in python with "test"

the error line 62 of model_part.cpp is returned
`KRATOS_ERROR_IF( NewName.empty() ) << "Please don't use empty names (\"\") when creating a ModelPart" << std::endl;`

**Comment by RiccardoRossi** [comment] 2018-04-02 17:50
Hi @PhilippeBussetta could you post a minimal reproducer? ideally as a test in the test_model_part.py

**Comment by loumalouomega** [comment] 2018-04-02 20:50
Or a Cpp test if you are using c++ constructor

**Comment by PhilippeBussetta** [comment] 2018-04-02 22:00
I used the test CLs .py
Maybe it is a pb at the python and C++ interface

**Comment by PhilippeBussetta** [comment] 2018-04-03 10:31
Hi, @RiccardoRossi I have the same problem with the official version under Windows and FullDebug (under Linux the problem does not appear):
`..\..\..\runkratos.exe test_constitutive_law.py`

the error line 61 of [model_part.cpp](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/sources/model_part.cpp) is returned
KRATOS_ERROR_IF( NewName.empty() ) << "Please don't use empty names (\"\") when creating a ModelPart" << std::endl;

**Comment by PhilippeBussetta** [comment] 2018-04-04 10:56
Ping @KratosMultiphysics/structural-mechanics

**Comment by RiccardoRossi** [comment] 2018-04-04 12:42
@roigcarlo, i am writing you since i know you are compiling in windows. Once you are done could you try this out?

@PhilippeBussetta can u try to do 
      
     std::cout << NewName << " is empty = " << NewName.empty() << std::endl;

**Comment by roigcarlo** [comment] 2018-04-04 12:46
I'll take a look

**Comment by PhilippeBussetta** [comment] 2018-04-04 13:02
In release:
```

..\..\..\runkratos.exe test_constitutive_law.py
 |  /           |
 ' /   __| _` | __|  _ \   __|
 . \  |   (   | |   (   |\__ \
_|\_\_|  \__,_|\__|\___/ ____/
           Multi-Physics 6.0.0-7b650a91b8-Debug
Importing    KratosStructuralMechanicsApplication
     KRATOS   ___|  |                   |                   |
            \___ \  __|  __| |   |  __| __| |   |  __| _` | |
                  | |   |    |   | (    |   |   | |   (   | |
            _____/ \__|_|   \__,_|\___|\__|\__,_|_|  \__,_|_| MECHANICS
test is empty = 0
.test is empty = 0
.test is empty = 0
.test is empty = 0
.test is empty = 0
.test is empty = 0
.test is empty = 0
.test is empty = 0
.test is empty = 0
.test is empty = 0
.test is empty = 0
.test is empty = 0
.test is empty = 0
.test is empty = 0
.test is empty = 0
.
----------------------------------------------------------------------
Ran 15 tests in 0.159s

OK
```

In FullDebug:

It is not possible to read `NewName`

![image](https://user-images.githubusercontent.com/28304076/38309250-76bbe758-3811-11e8-99d3-67f17b0ae1dd.png)

**Comment by RiccardoRossi** [comment] 2018-04-04 13:29
@PhilippeBussetta honestly i cannot see any problem in this. 

Could it be that you are running with a version of python different from the one you compiled the debug version with?

**Comment by PhilippeBussetta** [comment] 2018-04-04 13:54
@RiccardoRossi 
I don't think, I have installed only one version of python -- 3.6 and it is first in the path.
The Cmake configuration is the same with adding `python36_d.lib` to the `DPYTHON_LIBRARY`

**Comment by pooyan-dadvand** [comment] 2018-04-06 12:40
Seems to be a library inconsistency as @RiccardoRossi mentioning. Would you please try a clean compile removing completely your build directories?

**Comment by RiccardoRossi** [comment] 2018-04-15 18:59
@PhilippeBussetta we now passed to pybind and all the wrapping changed. could u check if there has been a change with this?

**Comment by PhilippeBussetta** [comment] 2018-04-16 14:54
@pooyan-dadvand I tried without success.
@RiccardoRossi It seems that it is due to boost -- 1.66. The problem disappear with the new version with pybind

**Comment by RiccardoRossi** [comment] 2018-04-16 15:04
oh if it works with pybind that's good... we can close this as solved :-)

**Closed as completed by RiccardoRossi** 2018-04-16 15:04 UTC
Labels: Windows, Error, Debug
