### ISSUE TITLE
FEM explicit dynamic solver - No difference - changing Damping parameters.

### ISSUE THREAD

**Issue by akhilkmat** [KratosMultiphysics/Kratos#11107] opened 2023-05-10 16:23 UTC
**Description**

Hi all,

As part of initial problem setup for a coupled DEM-FEM problem, I am trying to simulate a simple FEM structural analysis problem using Dynamic solver.

The problem consists of a small column resting on 4 fixed nodes in gravity.
Domain 0.02 x 0.02 x 0.16 (height) - 8 cube elements of size 0.02 x 0.02 x 0.02. 
The bottom most 4 nodes are fixed.
The simulations lasts 0.5 sec real time.

Problem:
1. When i analyze the reaction from the bottom fixed nodes (images attached), it keeps on oscillating about a mean value, even after changing the Rayleigh_alpha and Rayleigh_beta coefficients ( coefficients are changed over a wide range), there is no change in the graph at all for varying coefficient values; i wonder whether the solver actually reads the input values? or am I missing something? (Ps: i tried both linear and non linear analysis as well)

2. I ran the same problem in static solver and it gives me expected results ie.. weight = reaction. Although the reaction in the static solver is positive and in the dynamic solver it is negative but the magnitude of the mean value of reaction in the dynamic solver is almost same as the magnitude of static solver. The reaction is expected to be positive since gravity acts in the -ive direction. I wonder whether the dynamic solver has a different sign convention compared to the static solver?

I am attaching the projectparameter.json file (in .txt extention) and some images for your reference, the displacement graph shows the displacement of one of the nodes just above the fixed node.
[ProjectParameters.txt](https://github.com/KratosMultiphysics/Kratos/files/11444162/ProjectParameters.txt)
![reaction](https://github.com/KratosMultiphysics/Kratos/assets/69186170/c97ff4f1-711b-447e-8862-4082fe95bba1)
![displacement_lowest element-top nod
[ProjectParameters.txt](https://github.com/KratosMultiphysics/Kratos/files/11444155/ProjectParameters.txt)
e 32](https://github.com/KratosMultiphysics/Kratos/assets/69186170/d84c6b9a-0611-43e4-bf81-ea079dce6b16)

Please help,
Best,
Akhil Mathews

**Scope**
FEM
structure

**Comment by AlejandroCornejo** [comment] 2023-05-11 11:54
is here any reason that you use explicit? Can you try to see if in implicit oyu get the same result?

@loumalouomega

**Comment by AlejandroCornejo** [comment] 2023-05-11 11:56
Maybe 1.0e-5 s is still a big time step... Honestly i do not use explicit

**Comment by loumalouomega** [comment] 2023-05-11 12:18
Can you please share the whole case? 

I don't know if we are updating the RHS (only one computed in explicit) with the corresponding damping. I will need to check it. Can you check damping works in implicit?

**Comment by akhilkmat** [comment] 2023-05-11 14:02
Hi,

Thank you very much. Now I am getting the expected results.

![reaction](https://github.com/KratosMultiphysics/Kratos/assets/69186170/218f86e8-b466-4868-93a7-d9276f356020)

Best,
Akhil

**Comment by loumalouomega** [comment] 2023-05-11 17:33
Do you need to use the explicit?, if not can you at least share the case, so I can debug it. Despite explicit not being our strong point, I would like to have a consistent behaviour between both of them.

**Comment by loumalouomega** [comment] 2023-05-11 18:04
> Sure,
> 
> I do not need to use explicit. PFA. I was using explicit and central differences and changed to implicit and backward Euler after which it worked.
> 
> thanks, Akhil
> 
> [FEM_explicit.zip](https://github.com/KratosMultiphysics/Kratos/files/11455113/FEM_explicit.zip)

Should work with any implicit one, I will check for explicit.

**Comment by loumalouomega** [comment] 2023-05-11 18:11
> > Sure,
> > I do not need to use explicit. PFA. I was using explicit and central differences and changed to implicit and backward Euler after which it worked.
> > thanks, Akhil
> > [FEM_explicit.zip](https://github.com/KratosMultiphysics/Kratos/files/11455113/FEM_explicit.zip)
> 
> Should work with any implicit one, I will check for explicit.

I can confirm that there is no damping contribution in the explicit scheme: https://github.com/KratosMultiphysics/Kratos/blob/master/applications/StructuralMechanicsApplication/custom_strategies/custom_schemes/explicit_central_differences_scheme.hpp 

This should be fixed, but I don't have time for it.

**Comment by rubenzorrilla** [comment] 2023-05-12 07:56
Lets leave the issue open to keep track of it. Thanks for reporting @akhilkmat.

**Comment by AlejandroCornejo** [comment] 2023-05-12 07:56
@ipouplana you are using explicit, can you give us a hint?

**Comment by loumalouomega** [comment] 2023-05-12 08:20
> @ipouplana you are using explicit, can you give us a hint?

The hint is that no damping term is added in the explicit schemes, BTW in explicit the damping should not consider stiffness term, otherwise is a killer

**Comment by ipouplana** [comment] 2023-05-12 10:19
I’ll take a look to see if there is something wrong in the implementation of the damping forces. However, if I remember correctly, the last time I ran a case using the explicit dynamic solver it worked as expected... Therefore, although I still need to check it out, the misbehaviour pointed out here could simply be due to an incorrect definition of the Rayleigh damping parameters. In any case, I’ll let you know if I see something off.

**Comment by ipouplana** [comment] 2023-05-15 08:32
Good morning, I may have found the reason why you didn’t get the expected damping when working with the explicit dynamic solver. You need to check whether you had the Rayleigh parameters stored in the Properties.

The thing is that, if you first look at the method `AddExplicitContribution` inside the _base_solid_element.cpp_, you can see that the `damping_residual_contribution` is calculated using the parameters `RAYLEIGH_ALPHA` and `RAYLEIGH_BETA` **taken from the Properties** and not from the `ProcessInfo`. However, if you then look at the method `_CreateScheme` inside the _structural_mechanics_explicit_dynamic_solver.py_, you can see that the Rayleigh parameters are stored as ProcessInfo variables. Thereby, the solution could either be to store those parameters also in the Properties when creating the scheme, or to add the possibility of reading those parameters from the ProcessInfo inside the element.

What do you think @loumalouomega @AlejandroCornejo ?

**Comment by loumalouomega** [comment] 2023-05-15 08:41
For coherence, we should consider properties always, because is a property of the material not something global

**Comment by rubenzorrilla** [comment] 2023-05-15 09:21
And what if we check both, giving priority to the property parameters.

**Comment by loumalouomega** [comment] 2023-05-15 09:23
> And what if we check both, giving priority to the property parameters.

That is what is done in some elements from the CableNetApp (main explicit structural app), I will set both and add a deprecation warning

**Closed as completed** 2023-05-22 11:55 UTC
Labels: Question, Discussion
