### ISSUE TITLE
Kratos path

### ISSUE THREAD

**Issue by PhilippeBussetta** [KratosMultiphysics/Kratos#421] opened 2017-05-19 10:21 UTC
I propose to add the command “os.path.abspath” into the file “KratosLoader.py” in order to make the path clearer.
[KratosLoader.zip](https://github.com/KratosMultiphysics/Kratos/files/1013829/KratosLoader.zip)

**Comment by jcotela** [comment] 2017-05-19 11:41
Hi Philippe. Thanks for your suggestion! We only have one minor problem: the KratosLoader file does not actually exist in the repository (it is "magically" generated by CMake when you install Kratos). I'll see how we can modify the generation script to incorporate this python change.

**Comment by jcotela** [comment] 2017-05-26 14:45
Philippe, I have incorporated your modifications to pull request #440. If you have the time, could you verify that the code in that branch behaves as you expect?

**Comment by PhilippeBussetta** [comment] 2017-05-26 15:31
Thank you, I will check.

**Comment by PhilippeBussetta** [comment] 2017-05-26 16:18
Great, everything is fine.

**Comment by jcotela** [comment] 2017-05-26 16:37
Ok, I'm merging PR #440 into master then. I'll close this, since the issue is solved. Thanks for your help!

**Closed as completed by jcotela** 2017-05-26 16:37 UTC
Labels: Cleanup, Python
