### ISSUE TITLE
#pragma once - do we use it now?

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#10229] opened 2022-09-05 21:11 UTC
basically see title

I saw this popping up in a few places, I think this should be discussed and agreed on once

**Comment by rubenzorrilla** [comment] 2022-09-06 07:15
The idea is to start promoting the use of `pragma once`. See [here](https://github.com/KratosMultiphysics/Kratos/pull/10016#discussion_r928602155). Closing as we already discussed this in the @KratosMultiphysics/technical-committee. @philbucher  feel free to reopen if you want to add something.

**Closed as completed by rubenzorrilla** 2022-09-06 07:15 UTC
Labels: Discussion, C++

**Comment by philbucher** [comment] 2022-09-08 20:41
awesome thx!

**Comment by sunethwarna** [comment] 2022-09-08 20:56
The '#pragma once' is supported since 2013 ryt ?( as per Wikipedia) ...i also love the idea :)... But little bit curious about the cause for the sudden behavior change :)

**Comment by philbucher** [comment] 2022-09-08 20:58
what behavior change?
