### ISSUE TITLE
residualbased_elimination_builder_and_solver  and "calculate_reactions" gives Segmentation Fault

### ISSUE THREAD

**Issue by josep-m-carbonell** [KratosMultiphysics/Kratos#1035] opened 2017-11-16 10:36 UTC
This happens when in the solver parameters there are:

"block_builder" : false,
"compute_reactions": true

**Comment by RiccardoRossi** [comment] 2017-11-16 13:10
can u prepare a small test case?

**Comment by josep-m-carbonell** [comment] 2017-11-16 14:28
Yes
[test_reactions_str.gid.zip](https://github.com/KratosMultiphysics/Kratos/files/1478860/test_reactions_str.gid.zip)

**Comment by jcotela** [comment] 2017-11-17 12:05
Thanks for the test, @josep-m-carbonell, looks like you have found a bug. The issue that causes your Segfault is that the BuilderAndSolver's SetUpDofSet is called before fixing the DOFs. There is a "hacky" fix for your problem, which is to move the solver initialization (lines 85-87 in MainKratos.py) to after `process.ExecuteBeforeSolutionLoop()` (currently on line 93).

The cause of the problem is that the process that fixes the DOF currently does so in the ExecuteBeforeSolutionLoop call, which is called after solver.Initialize. This is catastrophic for the elimination builder and solver, since it determines the size of vectors and matrices at a point were all dofs in the system are uninitialized (and free).

**Comment by josep-m-carbonell** [comment] 2017-11-17 13:02
Hello @jcotela. Thank you to look into the problem. I have tested your solution, but is still fails in my application. If this is something about fixing Dofs, in fact they are fixed in process.ExecuteInitializeSolutionStep(). The tricky thing is that in the core processes process.ExecuteBeforeSolutionLoop() calls  process.ExecuteInitializeSolutionStep(), but what happens if the Dofs change from one step to another? the initilization of the Solver would be needed again ?

**Comment by josep-m-carbonell** [comment] 2017-11-17 13:15
I have checked it, it does not gives segmentation fault, but it do not considers new dofs into the solution. I just gives a strange wrong result in the solution.

**Comment by jcotela** [comment] 2017-11-17 13:16
@josep-m-carbonell the issue is that the size of the system matrices is usually set at some point during  solver.Initialize (the strategy will call builder_and_solver's SetUpDofSet, SetUpSystem and ResizeAndInitializeVectors at some point, it depends on the specific one you are using), but here we are fixing the dofs after this point.

For the situation you describe (changing fixity during the problem), the strategy should have a flag called `ReformDofSetAtEachStep` (it is called like this in C, no idea about the json). The ResidualBasedLinearStrategy has it, and others deriving from it have it too. Setting it to `true` will ensure that the matrix sizes are re-calculated at each step, but it is not done by default because it is quite expensive. Alternatively, if you know exactly when dofs are added/removed, call strategy.Clear() before the next solve to force a re-calculation.

**Comment by josep-m-carbonell** [comment] 2017-11-17 13:37
Yes you are right. Activating the flag of "reform_dofs_at_each_step",  it solves the problem. Even if you do not change the order of the solver initialization. Why the block_builder does not need to activate this flag to consider that the dofs change?

**Comment by jcotela** [comment] 2017-11-17 13:44
The block builder and solver always builds the entire problem matrix (free+fixed DOFs) and sets to zero rows/columns for fixed DOFs, the elimination one only builds the free rows/columns.

The segfault came because the size of the reaction vector in the elimination solver is equal to the number of fixed DOF, which was being wrongly set to 0 in this test, since the DOFs were not fixed yet.

To be honest, I never tested the block builder and solver in the context (changing dofs), but it has the advantage that the matrix sizes are constant as long as no nodes are added/removed. I guess you were "lucky" here, because you only fix/free existing nodes, but I expect it to fail too if you add or remove nodes from the problem.

**Comment by josep-m-carbonell** [comment] 2017-11-17 13:52
Ok, understood. Thank you very much @jcotela

**Comment by RiccardoRossi** [comment] 2017-11-17 15:32
Just to tell that the answer of @jcotela is correct:

the block builder and solver, constructs the graph of the entire problem, and then sets the dirichlet BCs by putting a 1 in the diagonal and setting to zero the whole row and column.
This procedure allows to fix/unfix dofs freely _**as long as the graph of the system is not changed**_ 

The elimination_builder_and_solver on the contrary does not form the rows and columns corresponding to the eliminated dofs (the elimination in the name indicates this). As a consequence you must recompute the graph (which is very expensive) every time you change the fixity.
The advantage is of course that the system to be solved is smaller (however it does not preserve the block structure of the dofs, which makes it unsuitable with using it with amgcl).

an alternative solution to the ReformDof flag is to call the function 
       
     strategy.Clear()

after the solve if you know that the graph will change

**Comment by josep-m-carbonell** [comment] 2017-11-17 16:08
Thank you @RiccardoRossi  and @jcotela. 

The question arising from this is, how a process that is going to modify dofs can set the strategy parameters (ReformDofs flag or Clear() ) that are in the solver class?

**Comment by RiccardoRossi** [comment] 2017-11-17 16:35
the short answer is: it can not...

**Comment by RiccardoRossi** [comment] 2017-11-17 16:48
longer answer is: i don't know how this can be accomplished while preserving the modularity.

i think it would make sense that the "BoundaryProcessList" is passed to the Strategy which is then aware of what is being done.  Still i don't have a good solution for this

**Comment by jcotela** [comment] 2017-11-17 19:03
@josep-m-carbonell The simplest solution I can think of would be having your process set some flag in ProcessInfo and your solver (or your main script) then call Clear if the flag is true, but that would then be specific for that script and, as @RiccardoRossi says, would break modularity (so, at this point, you might want to skip the process altogether and add a function in your solver that does the same thing).

**Comment by RiccardoRossi** [comment] 2017-11-18 08:41
I would say that this is something that belongs to the main.

we could do something lie 

     strategy.ClearIfNeeded(GRAPH_IS_CHANGED, FIXITY_IS_CHANGED)

     strategy.Predict()
     strategy.InitializeSolutionStep()
     strategy.SolveSolutionStep()
     strategy.FinalizeSolutionStep()

then at the end of the step we would need to reset the flags

    ProcessInfo.SetValue(FIXITY_IS_CHANGED, False)
    ProcessInfo.SetValue(GRAPH_IS_CHANGED, False)

however i don't see any good way of deciding automatically if the graph changes other than telling it at construction time

**Comment by RiccardoRossi** [comment] 2017-11-26 16:59
we commented the ResidualBasedElimination from the interface of the StructuralApplciation.

I think this issue can be either closed or the name should be changed

**Comment by jcotela** [comment] 2017-11-27 08:13
Closing, I believe there are no remaining questions.

**Closed as completed by jcotela** 2017-11-27 08:13 UTC
Labels: Bug, Python
