### ISSUE TITLE
Projecting Gradients on surface normals

### ISSUE THREAD

**Issue by armingeiser** [KratosMultiphysics/Kratos#1026] opened 2017-11-14 18:02 UTC
@dbaumgaertner For 3D4N shape optimization conditions the projection on the surface normals fails.
I assume the normal calculation gives wrong results. 
This happens in the eigenfrequency response branch, not tested yet in master

**Comment by pooyan-dadvand** [comment] 2017-12-13 09:26
@loumalouomega have you notice this in master branch?

**Comment by loumalouomega** [comment] 2017-12-13 11:06
I use the normal of the quadrilateral a lot for the contact application, I haven't noticed any problem, can you expand it?

**Comment by armingeiser** [comment] 2017-12-13 13:15
In 

https://github.com/KratosMultiphysics/Kratos/blob/master/applications/ShapeOptimizationApplication/custom_utilities/geometry_utilities.h#L140

we are using the ```CalculateOnSimplex(mrModelPart,domain_size)``` function.
This ends up in the function 
```void CalculateOnSimplex(ConditionsArrayType& rConditions,int dimension)```
where the normals are only calculated if the number of nodes == 3

https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/utilities/normal_calculation_utils.h#L137

So maybe we are using different normal calculation utilities?

**Comment by loumalouomega** [comment] 2017-12-13 13:17
I am using the normal implemented in the geometry, the utility is not needed (only if you want to average the normal between faces)

**Comment by armingeiser** [comment] 2017-12-13 13:21
I see. Unfortunately averaging the normals between faces is exactly what we want to do.

**Comment by loumalouomega** [comment] 2017-12-13 13:23
Still possible, I do that, but the local normal is computed using the geometry implementation->See: https://github.com/KratosMultiphysics/Kratos/blob/feature-reduce-contact-assembling/applications/ContactStructuralMechanicsApplication/custom_utilities/contact_utilities.h line 112

**Comment by armingeiser** [comment] 2017-12-13 13:42
Thanks for the hint, i think i could copy the function in order to keep the ShapeOptimizationApplication independent of the StructuralMechanicsApplication.

Or would it make more sene to extend the normal_calculation_utils::CalculateOnSimplex function?

**Comment by loumalouomega** [comment] 2017-12-13 13:49
I can move it to the core if the @KratosMultiphysics/technical-committee agrees

**Comment by RiccardoRossi** [comment] 2017-12-13 14:45
@armingeiser @loumalouomega i will take a look at this, and tell smthg asap

**Comment by loumalouomega** [comment] 2017-12-13 14:50
:smiley:

**Comment by pooyan-dadvand** [comment] 2018-01-22 16:37
Any news? Can we close this?

**Comment by dbaumgaertner** [comment] 2018-01-23 12:31
following that question. @loumalouomega Did you finally try to move your things to the core?

**Comment by loumalouomega** [comment] 2018-01-23 13:31
it wasn't me who proposed to move to the core, it was @RiccardoRossi , I can move if necessary

**Comment by dbaumgaertner** [comment] 2018-02-14 12:30
Let me refresh this issue again since we frequently require these averaged normals here.  The problem is that currently the calculation of averaged surface normals in "normal_calculation_utitls.h" fails with 3D4N geometries.

Now, I understand that we can compute the normals within our own application but I thought that using given features might be the better way, which is why I would opt for an adjustment of the above utils file. 

Assuming individually plane surface geometries, an easy extension to support the normal calculation for other planar geometries would be a removal of line 137 in [here](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/utilities/normal_calculation_utils.h). Is there any reason not to do this? Alternatively, one could add after this line:

`                if (it->GetGeometry().PointsNumber() == 4)`
`                    CalculateNormal3D(it,An,v1,v2);`

If ok, I can make a corresponding PR. If not I would be happy for other suggestions.

Thanks in advance.

**Closed as completed** 2018-02-14 15:38 UTC
