### ISSUE TITLE
[Core][Geometry] Bugs and possible error

### ISSUE THREAD

**Issue by bodhinandach** [KratosMultiphysics/Kratos#3351] opened 2018-11-13 14:44 UTC
I was discovering with @adityaghantasala yesterday and discussed with @roigcarlo this morning that there could be a minor bug which can lead to problems in geometry.

So I somehow run the following comment from my element to clear the geometry in C++:
`element_itr->GetGeometry().clear();`

This results in an error raised if I call `element.GetGeometry()` and an empty node list [ ] if I call
`element.GetNodes()` from a python script. Which is expected

However, surprisingly if I call `element.GetNode(index).Id `or `element.GetNode(index).X` or  `element.GetNode(index).something`, this will return me the previous `node(index).something` that is stored before it is cleared.

I am not saying that the node should be deleted, but I think that `GetNode(index).something` should return me a raise, cause it's empty basically.

This may lead to problems if suppose someone is blindly calling the above functions without knowledge that the element's geometry has been cleared. Hence, it will indeed produce wrong results without knowing that they are calling old nodal entities. 

Perhaps the @pooyan-dadvand and @RiccardoRossi can take a look on it further? Many thanks in advance.

**Comment by loumalouomega** [comment] 2018-11-13 14:56
The geometry derives from PointerVector. I already found some features that I think that can be considered as bugs. This class uses a std::vector to store the pointers. It is supposed to be empty once clear() is done.  I suggest to create a cpp test for this class and checks that all the behaviors are expected.

**Comment by roigcarlo** [comment] 2018-11-13 16:22
As I told @bodhinandach this morning I suspect (I'm sure) the problem appears because the GetNode(i) function from the wrappers is directly accessing the PointerVector<Nodes> without checking the size of such vector.

Like in many other places, C++ only marks that position as invalid after a `clear()`, but it actually doesn't fully delete the information. If you access a given position afterwards, chances are the data will still be there. 
Out of bounds access is not per-se an error, from the compiler point of view, but its classified as an operation with a undefined behavior which is this case simply returns the data normally as nobody has overwritten it.

It may seem a bug, its also possible that this is done intentionally to improve performance. As a matter of fact, I believe the responsibility to check the scope of the access in this particular case is on the user hands, and we should not ensure that what is being done is valid.

Another good point is that probably we should extend the `HadNode(i)` function to python, since right now the only way to ensure a given node exists from python is no iterate over the list of all nodes...

As I don't know the answer I suggested to make an issue to discuss it tomorrow during the @KratosMultiphysics/technical-committee meeting so we can discuss, but feel free to add your ideas here as well.

**Comment by loumalouomega** [comment] 2018-11-13 16:33
Agree with @roigcarlo, but I still think we should create a cpp test for VectorPointer, and document the expected behavior (and think how to remove the dependence of the class from boost)

**Comment by pooyan-dadvand** [comment] 2018-11-14 11:22
@KratosMultiphysics/technical-committee considers the option of having a debug check in access operator  but the effect of this addition to the performance in full debug is an issue.

**Comment by bodhinandach** [comment] 2018-11-28 07:48
@pooyan-dadvand @roigcarlo I assume that the @KratosMultiphysics/technical-committee are aware of this issue and I am closing this to reduce the number of opened issues.

**Comment by pooyan-dadvand** [comment] 2019-02-20 11:50
@bodhinandach would you please tell us why this issue is reopened?

**Comment by maceligueta** [comment] 2019-03-01 09:56
ping @bodhinandach

**Comment by bodhinandach** [comment] 2019-03-01 10:20
Sorry, @pooyan-dadvand @maceligueta for the late reply. I closed it since I thought the discussion is over. But I reopened it since I saw that was still "To Do" in the Technical Committee projects.

**Comment by bodhinandach** [comment] 2019-03-01 10:22
This issue was just a comment, but if you think that it should stay as it is, please feel free to close it.

**Comment by jcotela** [comment] 2019-03-01 10:23
Thanks @bodhinandach for the clarification. Closing, then.

**Closed as completed by jcotela** 2019-03-01 10:23 UTC
Labels: Bug, Question
