### ISSUE TITLE
i am trying to compile the kratos but meet questions when run the configure.bat.

### ISSUE THREAD

**Issue by Ada2045lalala** [KratosMultiphysics/Kratos#11935] opened 2024-01-09 06:56 UTC
**Description**
# i am trying to compile kratos by following the See INSTALL.md. However ,i meet some trouble.
I'm using Windows 10, Python 3.12.1, Cmake 3.28.1, Boost 1.84.
# there is my configure.bat

`@echo off
rem Please do not modify this script

rem For any question please contact with us in:
rem  - https://github.com/KratosMultiphysics/Kratos

rem Optional parameters:
rem You can find a list will all the compiation options in INSTALL.md or here:
rem  - https://github.com/KratosMultiphysics/Kratos/wiki/Compilation-options

rem Set compiler
set CC=cl.exe
set CXX=cl.exe

rem Set variables
if not defined KRATOS_SOURCE set KRATOS_SOURCE=%~dp0..
if not defined KRATOS_BUILD set KRATOS_BUILD=%KRATOS_SOURCE%/build

rem Warning: In windows this option only works if you run through a terminal with admin privileges
rem set KRATOS_INSTALL_PYTHON_USING_LINKS=ON

rem Set basic configuration
if not defined KRATOS_BUILD_TYPE set KRATOS_BUILD_TYPE=Release
if not defined BOOST_ROOT set BOOST_ROOT=D:\KratosMultiPhysics\boost_1_84_0
if not defined PYTHON_EXECUTABLE set PYTHON_EXECUTABLE=C:\Windows\py.exe

rem Set applications to compile
set KRATOS_APP_DIR=applications
set KRATOS_APPLICATIONS=
CALL :add_app %KRATOS_APP_DIR%\LinearSolversApplication;
CALL :add_app %KRATOS_APP_DIR%\StructuralMechanicsApplication;
CALL :add_app %KRATOS_APP_DIR%\FluidDynamicsApplication;

rem Clean
del /F /Q "%KRATOS_BUILD%\%KRATOS_BUILD_TYPE%\cmake_install.cmake"
del /F /Q "%KRATOS_BUILD%\%KRATOS_BUILD_TYPE%\CMakeCache.txt"
del /F /Q "%KRATOS_BUILD%\%KRATOS_BUILD_TYPE%\CMakeFiles"

rem Enable this if your build is slow and you have a multi-core machine
rem set KRATOS_PARALLEL_BUILD_FLAG=/MP4

rem Configure
@echo on
cmake -G"Visual Studio 16 2019" -H"%KRATOS_SOURCE%" -B"%KRATOS_BUILD%\%KRATOS_BUILD_TYPE%"          ^
-DUSE_EIGEN_MKL=OFF                                                                                 ^
-DCMAKE_CXX_FLAGS=" %KRATOS_PARALLEL_BUILD_FLAG% "                                                  ^
-DKRATOS_GENERATE_PYTHON_STUBS=ON

rem Build
cmake --build "%KRATOS_BUILD%/%KRATOS_BUILD_TYPE%" --target install -- /property:configuration=%KRATOS_BUILD_TYPE% /p:Platform=x64
goto:eof

rem Function to add apps
:add_app
set KRATOS_APPLICATIONS=%KRATOS_APPLICATIONS%%1;
goto:eof
`
# And there is the result
![2024-01-09 (2)](https://github.com/KratosMultiphysics/Kratos/assets/155991150/4bff5cd8-02a2-48f1-957a-cbbf881fff37)

PS D:\KratosMultiPhysics\Kratos\scripts> .\configure.bat

D:\KratosMultiPhysics\Kratos\scripts>cmake -G"Visual Studio 16 2019" -H"D:\KratosMultiPhysics\Kratos\scripts\.." -B"D:\KratosMultiPhysics\Kratos\scripts\../build\Release"          -DUSE_EIGEN_MKL=OFF                                                                                 -DCMAKE_CXX_FLAGS="  "                                                  -DKRATOS_GENERATE_PYTHON_STUBS=ON
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19045.
-- The C compiler identification is MSVC 19.29.30153.0
-- The CXX compiler identification is MSVC 19.29.30153.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: D:/Software/Visual Studio Community 2019/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: D:/Software/Visual Studio Community 2019/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- No KRATOS_SOURCE_DIR is defined, using: D:/KratosMultiPhysics/Kratos
-- No KRATOS_BINARY_DIR is defined, using: D:/KratosMultiPhysics/Kratos/build/Release
-- No KRATOS_INSTALL_PYTHON_USING_LINKS is defined, setting to OFF
-- No CMAKE_INSTALL_MESSAGE is defined. Setting to NEVER
-- Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.43.0.windows.1")
-- CMAKE_SYSTEM_NAME = Windows
-- CMAKE_CXX_COMPILER_ID = MSVC
-- CMAKE_CXX_FLAGS =
-- CMAKE_C_FLAGS = /DWIN32 /D_WINDOWS /W3
Detected compiler as MSVC
CMake Deprecation Warning at cmake_modules/pybind11Tools.cmake:8 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.
Call Stack (most recent call first):
  CMakeLists.txt:291 (include)

CMake Warning (dev) at cmake_modules/FindPythonLibsNew.cmake:60 (find_package):
  Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
  are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

Call Stack (most recent call first):
  cmake_modules/pybind11Tools.cmake:16 (find_package)
  CMakeLists.txt:291 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found PythonInterp: C:\Windows\py.exe (found version "3.12.1")
-- Found PythonLibs: C:/Users/xxx/AppData/Local/Programs/Python/Python312/libs/Python312.lib
-- LTO is Disabled
-- AR VERSION: D:/Software/Visual Studio Community 2019/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/lib.exe
-- Python version used for the interface will be 3.12
-- Standard install dir D:/KratosMultiPhysics/Kratos/bin/Release
-- "KRATOS_SHARED_MEMORY_PARALLELIZATION" not defined, defaulting to "OpenMP"
-- Found OpenMP_C: -openmp (found version "2.0")
-- Found OpenMP_CXX: -openmp (found version "2.0")
-- Found OpenMP: TRUE (found version "2.0")
-- Using OpenMP for shared memory parallelization
CMake Warning (dev) at CMakeLists.txt:390 (find_package):
  Policy CMP0144 is not set: find_package uses upper-case <PACKAGENAME>_ROOT
  variables.  Run "cmake --help-policy CMP0144" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  CMake variable BOOST_ROOT is set to:

    D:\KratosMultiPhysics\boost_1_84_0

  For compatibility, find_package is ignoring the variable, but code in a
  .cmake module might still use it.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found Boost: D:/KratosMultiPhysics/msys64/mingw64/lib/cmake/Boost-1.84.0/BoostConfig.cmake (found version "1.84.0")
-- Boost Include: D:/KratosMultiPhysics/msys64/mingw64/include
-- Boost Linkdir:
-- Found ZLIB: D:/KratosMultiPhysics/msys64/mingw64/lib/libz.dll.a (found version "1.3")

-- CMAKE_BUILD_TYPE ........ Release

WARNING: YOUR GIDPOST IS BEING COMPILED  WITHOUT DEBUG (ALL ASSERTS WILL BE AVOIDED)
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - not found
-- Found Threads: TRUE
-- Configuring applications (ENV):
        Adding application 'applications\LinearSolversApplication'
**** configuring KratosLinearSolversApplication ****
CMake Deprecation Warning at cmake_modules/pybind11Tools.cmake:8 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.
Call Stack (most recent call first):
  applications/LinearSolversApplication/CMakeLists.txt:17 (include)

        Adding application 'applications\StructuralMechanicsApplication'
**** configuring KratosStructuralMechanicsApplication ****
CMake Deprecation Warning at cmake_modules/pybind11Tools.cmake:8 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.
Call Stack (most recent call first):
  applications/StructuralMechanicsApplication/CMakeLists.txt:6 (include)

        Adding application 'applications\FluidDynamicsApplication'
**** configuring KratosFluidDynamicsApplication ****

***********************************************************************

        LIST OF APPLICATIONS THAT ARE GOING TO BE COMPILED:

        LinearSolversApplication
        StructuralMechanicsApplication
        FluidDynamicsApplication

        APPLICATIONS ADDED TO COMPILATION THROUGH DEPENDENCIES:

***********************************************************************

List of upcoming API-breaking and behavior changes:
         Geometry 'Dimension' removed: https://github.com/KratosMultiphysics/Kratos/pull/10977
         Geometry old projection methods deprecation: https://github.com/KratosMultiphysics/Kratos/pull/9024
         Geometry old closest point methods deprecation: https://github.com/KratosMultiphysics/Kratos/pull/9243
         Model 'CreateModelPart' behavior change (no error thrown if model part exists): https://github.com/KratosMultiphysics/Kratos/pull/9598
         Make GetIntegrationMethod method of Condition const: https://github.com/KratosMultiphysics/Kratos/pull/9769
         Behavior change of ModelPart.GetProperties (MeshIndex removed): https://github.com/KratosMultiphysics/Kratos/pull/9774
         Behavior change of Testing. Please ensure you use KRATOS_EXPECT for testing instead of KRATOS_CHECK
-- clipper : D:/KratosMultiPhysics/Kratos/external_libraries/clipper
-- tinyexpr : D:/KratosMultiPhysics/Kratos/external_libraries/tinyexpr/tinyexpr/
-- Configuring done (20.0s)
-- Generating done (1.2s)
-- Build files have been written to: D:/KratosMultiPhysics/Kratos/build/Release

D:\KratosMultiPhysics\Kratos\scripts>rem Build

D:\KratosMultiPhysics\Kratos\scripts>cmake --build "D:\KratosMultiPhysics\Kratos\scripts\../build/Release" --target install -- /property:configuration=Release /p:Platform=x64
用于 .NET Framework 的 Microsoft (R) 生成引擎版本 16.11.2+f32259642
版权所有(C) Microsoft Corporation。保留所有权利。

  kratos_version.cpp
D:\Software\Visual Studio Community 2019\VC\Tools\MSVC\14.29.30133\include\vcruntime.h(351,51): error C2065: “uintptr_t”: 未声明的标识符 [D:\KratosMultiPhysics\Kra
tos\build\Release\kratos\KratosVersion.vcxproj]
D:\Software\Visual Studio Community 2019\VC\Tools\MSVC\14.29.30133\include\vcruntime.h(351,61): error C2146: 语法错误: 缺少“)”(在标识符“_StackCookie”的前面) [D:\KratosMu
ltiPhysics\Kratos\build\Release\kratos\KratosVersion.vcxproj]
D:\Software\Visual Studio Community 2019\VC\Tools\MSVC\14.29.30133\include\vcruntime.h(352,67): error C2065: “uintptr_t”: 未声明的标识符 [D:\KratosMultiPhysics\Kra
tos\build\Release\kratos\KratosVersion.vcxproj]
D:\Software\Visual Studio Community 2019\VC\Tools\MSVC\14.29.30133\include\vcruntime.h(352,77): error C2146: 语法错误: 缺少“)”(在标识符“_StackCookie”的前面) [D:\KratosMu
ltiPhysics\Kratos\build\Release\kratos\KratosVersion.vcxproj]
D:\Software\Visual Studio Community 2019\VC\Tools\MSVC\14.29.30133\include\vcruntime.h(356,18): error C2146: 语法错误: 缺少“;”(在标识符“__security_cookie ”的前面) [D:\Kra
tosMultiPhysics\Kratos\build\Release\kratos\KratosVersion.vcxproj]
D:/KratosMultiPhysics/msys64/mingw64/include\corecrt.h(75,53): error C2378: “uintptr_t”: 重定义；符号不能由 typedef 重载 [D:\KratosMultiPhysics\Kratos\build\Release\kr
atos\KratosVersion.vcxproj]
D:\Software\Visual Studio Community 2019\VC\Tools\MSVC\14.29.30133\include\vcruntime.h(356): message : 参见“uintptr_t”的声明 [D:\KratosMultiPhysics\Kratos\build\
Release\kratos\KratosVersion.vcxproj]
D:/KratosMultiPhysics/msys64/mingw64/include\stdio.h(195,64): error C2144: 语法错误:“int”的前面应有“;” [D:\KratosMultiPhysics\Kratos\build\Release\kratos\KratosVersi
on.vcxproj]
D:/KratosMultiPhysics/msys64/mingw64/include\stdio.h(198,69): error C2144: 语法错误:“int”的前面应有“;” [D:\KratosMultiPhysics\Kratos\build\Release\kratos\KratosVersi
on.vcxproj]
D:/KratosMultiPhysics/msys64/mingw64/include\stdio.h(201,87): error C2144: 语法错误:“int”的前面应有“;” [D:\KratosMultiPhysics\Kratos\build\Release\kratos\KratosVersi
on.vcxproj]
D:/KratosMultiPhysics/msys64/mingw64/include\stdio.h(204,92): error C2144: 语法错误:“int”的前面应有“;” [D:\KratosMultiPhysics\Kratos\build\Release\kratos\KratosVersi
on.vcxproj]
D:/KratosMultiPhysics/msys64/mingw64/include\stdio.h(207,87): error C2144: 语法错误:“int”的前面应有“;” [D:\KratosMultiPhysics\Kratos\build\Release\kratos\KratosVersi
on.vcxproj]
D:/KratosMultiPhysics/msys64/mingw64/include\stdio.h(210,92): error C2144: 语法错误:“int”的前面应有“;” [D:\KratosMultiPhysics\Kratos\build\Release\kratos\KratosVersi
on.vcxproj]
D:/KratosMultiPhysics/msys64/mingw64/include\stdio.h(213,88): error C2144: 语法错误:“int”的前面应有“;” [D:\KratosMultiPhysics\Kratos\build\Release\kratos\KratosVersi
on.vcxproj]
D:/KratosMultiPhysics/msys64/mingw64/include\stdio.h(216,93): error C2144: 语法错误:“int”的前面应有“;” [D:\KratosMultiPhysics\Kratos\build\Release\kratos\KratosVersi
on.vcxproj]
D:/KratosMultiPhysics/msys64/mingw64/include\stdio.h(230,61): error C2144: 语法错误:“int”的前面应有“;” [D:\KratosMultiPhysics\Kratos\build\Release\kratos\KratosVersi
on.vcxproj]
D:/KratosMultiPhysics/msys64/mingw64/include\stdio.h(233,66): error C2144: 语法错误:“int”的前面应有“;” [D:\KratosMultiPhysics\Kratos\build\Release\kratos\KratosVersi
on.vcxproj]
D:/KratosMultiPhysics/msys64/mingw64/include\stdio.h(236,84): error C2144: 语法错误:“int”的前面应有“;” 
D:/KratosMultiPhysics/msys64/mingw64/include\stdio.h(313,1): error C2447: “{”: 缺少函数标题(是否是老式的形式表?) [D:\KratosMultiPhysics\Kratos\build\Release\external_libra
ries\clipper\clipper.vcxproj]
D:/KratosMultiPhysics/msys64/mingw64/include\stdio.h(323,1): error C2062: 意外的类型“int” [D:\KratosMultiPhysics\Kratos\build\Release\external_libraries\clipper\
clipper.vcxproj]
D:/KratosMultiPhysics/msys64/mingw64/include\stdio.h(324,1): error C2143: 语法错误: 缺少“;”(在“{”的前面) [D:\KratosMultiPhysics\Kratos\build\Release\external_librarie
s\clipper\clipper.vcxproj]
D:/KratosMultiPhysics/msys64/mingw64/include\stdio.h(324,1): error C2447: “{”: 缺少函数标题(是否是老式的形式表?) [D:\KratosMultiPhysics\Kratos\build\Release\external_libra
ries\clipper\clipper.vcxproj]
D:/KratosMultiPhysics/msys64/mingw64/include\stdio.h(340,1): error C2062: 意外的类型“int” [D:\KratosMultiPhysics\Kratos\build\Release\external_libraries\clipper\
clipper.vcxproj]
D:/KratosMultiPhysics/msys64/mingw64/include\stdio.h(341,1): error C2143: 语法错误: 缺少“;”(在“{”的前面) [D:\KratosMultiPhysics\Kratos\build\Release\external_librarie
s\clipper\clipper.vcxproj]
D:/KratosMultiPhysics/msys64/mingw64/include\stdio.h(341,1): error C2447: “{”: 缺少函数标题(是否是老式的形式表?) [D:\KratosMultiPhysics\Kratos\build\Release\external_libra
ries\clipper\clipper.vcxproj]
D:/KratosMultiPhysics/msys64/mingw64/include\stdio.h(347,1): error C2062: 意外的类型“int” [D:\KratosMultiPhysics\Kratos\build\Release\external_libraries\clipper\
clipper.vcxproj]
D:/KratosMultiPhysics/msys64/mingw64/include\stdio.h(348,1): error C2143: 语法错误: 缺少“;”(在“{”的前面) [D:\KratosMultiPhysics\Kratos\build\Release\external_librarie
s\clipper\clipper.vcxproj]
D:/KratosMultiPhysics/msys64/mingw64/include\stdio.h(348,1): error C2447: “{”: 缺少函数标题(是否是老式的形式表?) [D:\KratosMultiPhysics\Kratos\build\Release\external_libra
ries\clipper\clipper.vcxproj]
D:/KratosMultiPhysics/msys64/mingw64/include\stdio.h(354,1): error C2062: 意外的类型“int” [D:\KratosMultiPhysics\Kratos\build\Release\external_libraries\clipper\
clipper.vcxproj]
D:/KratosMultiPhysics/msys64/mingw64/include\stdio.h(355,1): error C2143: 语法错误: 缺少“;”(在“{”的前面) [D:\KratosMultiPhysics\Kratos\build\Release\external_librarie
s\clipper\clipper.vcxproj]
D:/KratosMultiPhysics/msys64/mingw64/include\stdio.h(355,1): error C2447: “{”: 缺少函数标题(是否是老式的形式表?) [D:\KratosMultiPhysics\Kratos\build\Release\external_libra
ries\clipper\clipper.vcxproj]
D:/KratosMultiPhysics/msys64/mingw64/include\stdio.h(368,1): error C2062: 意外的类型“int” [D:\KratosMultiPhysics\Kratos\build\Release\external_libraries\clipper\
clipper.vcxproj]
D:/KratosMultiPhysics/msys64/mingw64/include\stdio.h(369,1): error C2143: 语法错误: 缺少“;”(在“{”的前面) [D:\KratosMultiPhysics\Kratos\build\Release\external_librarie
s\clipper\clipper.vcxproj]
D:/KratosMultiPhysics/msys64/mingw64/include\stdio.h(369,1): error C2447: “{”: 缺少函数标题(是否是老式的形式表?) [D:\KratosMultiPhysics\Kratos\build\Release\external_libra
ries\clipper\clipper.vcxproj]
D:/KratosMultiPhysics/msys64/mingw64/include\stdio.h(379,1): error C2062: 意外的类型“int” [D:\KratosMultiPhysics\Kratos\build\Release\external_libraries\clipper\
clipper.vcxproj]
D:/KratosMultiPhysics/msys64/mingw64/include\stdio.h(380,1): error C2143: 语法错误: 缺少“;”(在“{”的前面) [D:\KratosMultiPhysics\Kratos\build\Release\external_librarie
s\clipper\clipper.vcxproj]
D:/KratosMultiPhysics/msys64/mingw64/include\stdio.h(380,1): fatal error C1003: 错误计数超过 100；正在停止编译 [D:\KratosMultiPhysics\Kratos\build\Release\external_libra
ries\clipper\clipper.vcxproj]
  clipper.rectclip.cpp

D:/KratosMultiPhysics/msys64/mingw64/include\stdio.h(592,7): error C2059: 语法错误:“类型” [D:\KratosMultiPhysics\Kratos\build\Release\external_libraries\gidpost\g
idpost.vcxproj]
D:/KratosMultiPhysics/msys64/mingw64/include\stdio.h(599,7): error C2059: 语法错误:“类型” [D:\KratosMultiPhysics\Kratos\build\Release\external_libraries\gidpost\g
idpost.vcxproj]
D:/KratosMultiPhysics/msys64/mingw64/include\stdio.h(605,7): error C2059: 语法错误:“类型” [D:\KratosMultiPhysics\Kratos\build\Release\external_libraries\gidpost\g
idpost.vcxproj]
D:/KratosMultiPhysics/msys64/mingw64/include\stdio.h(924,7): error C2059: 语法错误:“类型” [D:\KratosMultiPhysics\Kratos\build\Release\external_libraries\gidpost\g
idpost.vcxproj]
D:/KratosMultiPhysics/msys64/mingw64/include\stdio.h(956,5): error C2059: 语法错误:“类型” [D:\KratosMultiPhysics\Kratos\build\Release\external_libraries\gidpost\g
idpost.vcxproj]
D:/KratosMultiPhysics/msys64/mingw64/include\stdio.h(1312,7): error C2059: 语法错误:“类型” [D:\KratosMultiPhysics\Kratos\build\Release\external_libraries\gidpost\
gidpost.vcxproj]
D:/KratosMultiPhysics/msys64/mingw64/include\stdio.h(1319,7): error C2059: 语法错误:“类型” [D:\KratosMultiPhysics\Kratos\build\Release\external_libraries\gidpost\
gidpost.vcxproj]
D:/KratosMultiPhysics/msys64/mingw64/include\stdio.h(1325,7): error C2059: 语法错误:“类型” [D:\KratosMultiPhysics\Kratos\build\Release\external_libraries\gidpost\
gidpost.vcxproj]
D:/KratosMultiPhysics/msys64/mingw64/include\stdio.h(1441,7): error C2059: 语法错误:“类型” [D:\KratosMultiPhysics\Kratos\build\Release\external_libraries\gidpost\
gidpost.vcxproj]
D:/KratosMultiPhysics/msys64/mingw64/include\stdio.h(1451,7): error C2059: 语法错误:“类型” [D:\KratosMultiPhysics\Kratos\build\Release\external_libraries\gidpost\
gidpost.vcxproj]
D:/KratosMultiPhysics/msys64/mingw64/include\swprintf.inl(27,5): error C2059: 语法错误:“类型” [D:\KratosMultiPhysics\Kratos\build\Release\external_libraries\gidpo
st\gidpost.vcxproj]
D:/KratosMultiPhysics/msys64/mingw64/include\swprintf.inl(34,5): error C2059: 语法错误:“类型” [D:\KratosMultiPhysics\Kratos\build\Release\external_libraries\gidpo
st\gidpost.vcxproj]

D:/KratosMultiPhysics/msys64/mingw64/include\stdlib.h(715,80): error C2085: “putenv”: 不在形参表中 [D:\KratosMultiPhysics\Kratos\build\Release\external_libraries\
gidpost\gidpost.vcxproj]
D:/KratosMultiPhysics/msys64/mingw64/include\stdlib.h(719,97): error C2085: “swab”: 不在形参表中 [D:\KratosMultiPhysics\Kratos\build\Release\external_libraries\gi
dpost\gidpost.vcxproj]
D:/KratosMultiPhysics/msys64/mingw64/include\stdlib.h(722,102): error C2085: “ultoa”: 不在形参表中 [D:\KratosMultiPhysics\Kratos\build\Release\external_libraries\
gidpost\gidpost.vcxproj]
D:/KratosMultiPhysics/msys64/mingw64/include\stdlib.h(723,42): error C2085: “onexit”: 不在形参表中 [
D:/KratosMultiPhysics/msys64/mingw64/include\stdio.h(1312,7): error C2059: 语法错误:“类型” [D:\KratosMultiPhysics\Kratos\build\Release\external_libraries\tinyexpr
\tinyexpr.vcxproj]
D:/KratosMultiPhysics/msys64/mingw64/include\stdio.h(1319,7): error C2059: 语法错误:“类型” [D:\KratosMultiPhysics\Kratos\build\Release\external_libraries\tinyexpr
\tinyexpr.vcxproj]
D:/KratosMultiPhysics/msys64/mingw64/include\stdio.h(1325,7): error C2059: 语法错误:“类型” [D:\KratosMultiPhysics\Kratos\build\Release\external_libraries\tinyexpr
\tinyexpr.vcxproj]
D:/KratosMultiPhysics/msys64/mingw64/include\stdio.h(1441,7): error C2059: 语法错误:“类型” [D:\KratosMultiPhysics\Kratos\build\Release\external_libraries\tinyexpr
\tinyexpr.vcxproj]
D:/KratosMultiPhysics/msys64/mingw64/include\stdio.h(1451,7): error C2059: 语法错误:“类型” [D:\KratosMultiPhysics\Kratos\build\Release\external_libraries\tinyexpr
\tinyexpr.vcxproj]
D:/KratosMultiPhysics/msys64/mingw64/include\swprintf.inl(27,5): error C2059: 语法错误:“类型” [D:\KratosMultiPhysics\Kratos\build\Release\external_libraries\tinye
xpr\tinyexpr.vcxproj]
D:/KratosMultiPhysics/msys64/mingw64/include\swprintf.inl(34,5): error C2059: 语法错误:“类型” [D:\KratosMultiPhysics\Kratos\build\Release\external_libraries\tinye
xpr\tinyexpr.vcxproj]
D:\KratosMultiPhysics\Kratos\external_libraries\tinyexpr\tinyexpr\tinyexpr.c(472,1): warning C4090: “初始化”: 不同的“const”限定符 [D:\KratosMultiPhysics\Kratos\build
\Release\external_libraries\tinyexpr\tinyexpr.vcxproj]
D:\KratosMultiPhysics\Kratos\external_libraries\tinyexpr\tinyexpr\tinyexpr.c(489,1): warning C4090: “初始化”: 不同的“const”限定符 [D:\KratosMultiPhysics\Kratos\build
\Release\external_libraries\tinyexpr\tinyexpr.vcxproj]
D:\KratosMultiPhysics\Kratos\external_libraries\tinyexpr\tinyexpr\tinyexpr.c(504,1): warning C4090: “初始化”: 不同的“const”限定符 [D:\KratosMultiPhysics\Kratos\build
\Release\external_libraries\tinyexpr\tinyexpr.vcxproj]

D:\KratosMultiPhysics\Kratos\scripts>goto:eof

# how to solve this problem?

**Scope**
- Compilation

**Comment by roigcarlo** [comment] 2024-01-09 08:51
Duplicate of https://github.com/KratosMultiphysics/Kratos/discussions/11934

@Ada2045lalala I am answering in the other link.

**Closed as completed by roigcarlo** 2024-01-09 08:51 UTC

**Comment by Ada2045lalala** [comment] 2024-01-09 09:27
Could you please infer me the link?

**Comment by Ada2045lalala** [comment] 2024-01-09 09:31
> Duplicate of #11934
> 
> @Ada2045lalala I am answering in the other link.

could you please tell  me the link?

**Comment by Ada2045lalala** [comment] 2024-01-09 09:32
@roigcarlo could you please tell me the link?
